from PyQt5 import QtWidgets
from _typeshed import Incomplete

class ElidedLabel(QtWidgets.QLabel):
    def __init__(self, parent: Incomplete | None = None) -> None: ...
    def setText(self, text) -> None: ...
    def resizeEvent(self, event) -> None: ...

class ActiveLabel(QtWidgets.QLabel):
    clicked: Incomplete
    def __init__(self, active: bool = True, drops: bool = False, *args) -> None: ...
    active: Incomplete
    def setActive(self, active) -> None: ...
    def mouseReleaseEvent(self, event) -> None: ...

class ClickableSlider(QtWidgets.QSlider):
    def mousePressEvent(self, event) -> None: ...
    def mouseMoveEvent(self, event) -> None: ...

class Popover(QtWidgets.QFrame):
    position: Incomplete
    def __init__(self, parent, position: str = "bottom") -> None: ...
    def show(self) -> None: ...
    def update_position(self) -> None: ...

class SliderPopover(Popover):
    value_changed: Incomplete
    label: Incomplete
    slider: Incomplete
    def __init__(self, parent, position, label, value) -> None: ...
