from PyQt5 import QtCore, QtWidgets
from _typeshed import Incomplete

class EditableListView(QtWidgets.QListView):
    def __init__(self, parent: Incomplete | None = None) -> None: ...
    def keyPressEvent(self, event) -> None: ...
    def mouseDoubleClickEvent(self, event) -> None: ...
    def closeEditor(self, editor, hint) -> None: ...
    def add_item(self, value: str = ""): ...
    def clear(self) -> None: ...
    def update(self, values) -> None: ...
    @property
    def items(self): ...
    def add_empty_row(self) -> None: ...
    def remove_selected_rows(self) -> None: ...
    def move_selected_rows_up(self) -> None: ...
    def move_selected_rows_down(self) -> None: ...
    def select_row(self, row) -> None: ...
    def select_key(self, value) -> None: ...
    def get_selected_rows(self): ...

class UniqueEditableListView(EditableListView):
    def __init__(self, parent: Incomplete | None = None) -> None: ...
    def setModel(self, model) -> None: ...
    def dropEvent(self, event) -> None: ...
    def on_data_changed(self, top_left, bottom_right, roles) -> None: ...

class EditableListModel(QtCore.QAbstractListModel):
    user_sortable_changed: Incomplete
    def __init__(
        self, items: Incomplete | None = None, parent: Incomplete | None = None
    ) -> None: ...
    @property
    def user_sortable(self): ...
    @user_sortable.setter
    def user_sortable(self, user_sortable) -> None: ...
    def sort(self, column, order=...): ...
    def get_display_name(self, item): ...
    def rowCount(self, parent=...): ...
    def data(self, index, role=...): ...
    def setData(self, index, value, role=...): ...
    def flags(self, index): ...
    def insertRows(self, row, count, parent=...): ...
    def removeRows(self, row, count, parent=...): ...
    @staticmethod
    def supportedDragActions(): ...
    @staticmethod
    def supportedDropActions(): ...
    def update(self, items) -> None: ...
    def move_row(self, row, new_row) -> None: ...
    @property
    def items(self): ...

class AutocompleteItemDelegate(QtWidgets.QItemDelegate):
    def __init__(self, completions, parent: Incomplete | None = None) -> None: ...
    def createEditor(self, parent, option, index): ...
