from PyQt5 import QtWidgets
from _typeshed import Incomplete
from picard.const import DEFAULT_PROFILE_NAME as DEFAULT_PROFILE_NAME
from picard.ui import HashableListWidgetItem as HashableListWidgetItem
from picard.util import unique_numbered_title as unique_numbered_title

class ProfileListWidget(QtWidgets.QListWidget):
    def contextMenuEvent(self, event) -> None: ...
    def keyPressEvent(self, event) -> None: ...
    def unique_profile_name(self, base_name: Incomplete | None = None): ...
    def add_profile(
        self, name: Incomplete | None = None, profile_id: str = ""
    ) -> None: ...
    def remove_selected_profile(self) -> None: ...
    def remove_profile(self, item) -> None: ...

class ProfileListWidgetItem(HashableListWidgetItem):
    profile_id: Incomplete
    def __init__(
        self, name: Incomplete | None = None, enabled: bool = True, profile_id: str = ""
    ) -> None: ...
    @property
    def pos(self): ...
    @property
    def name(self): ...
    @property
    def enabled(self): ...
    def get_all(self): ...
    def get_dict(self): ...
