from PyQt5 import QtGui
from PyQt5.QtWidgets import QCompleter, QTextEdit
from _typeshed import Incomplete
from collections.abc import Generator
from picard.config import BoolOption as BoolOption, get_config as get_config
from picard.const.sys import IS_MACOS as IS_MACOS
from picard.script import (
    ScriptFunctionDocError as ScriptFunctionDocError,
    script_function_documentation as script_function_documentation,
    script_function_names as script_function_names,
)
from picard.ui import FONT_FAMILY_MONOSPACE as FONT_FAMILY_MONOSPACE
from picard.ui.theme import theme as theme
from picard.util.tags import (
    PRESERVED_TAGS as PRESERVED_TAGS,
    TAG_NAMES as TAG_NAMES,
    display_tag_name as display_tag_name,
)

EXTRA_VARIABLES: Incomplete

def find_regex_index(regex, text, start: int = 0): ...

class TaggerScriptSyntaxHighlighter(QtGui.QSyntaxHighlighter):
    func_re: Incomplete
    func_fmt: Incomplete
    var_re: Incomplete
    var_fmt: Incomplete
    unicode_re: Incomplete
    unicode_fmt: Incomplete
    escape_re: Incomplete
    escape_fmt: Incomplete
    special_re: Incomplete
    special_fmt: Incomplete
    bracket_re: Incomplete
    noop_re: Incomplete
    noop_fmt: Incomplete
    rules: Incomplete
    def __init__(self, document) -> None: ...
    def highlightBlock(self, text) -> None: ...

class ScriptCompleter(QCompleter):
    last_selected: str
    def __init__(self, parent: Incomplete | None = None) -> None: ...
    @property
    def choices(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def all_tags(self) -> Generator[Incomplete, Incomplete]: ...
    def set_highlighted(self, text) -> None: ...
    def get_selected(self): ...

class DocumentedScriptToken:
    allowed_chars: Incomplete
    def __init__(self, doc, cursor_position) -> None: ...
    def is_start_char(self, char): ...
    def is_allowed_char(self, char, position): ...
    def get_tooltip(self, position) -> None: ...

class FunctionScriptToken(DocumentedScriptToken):
    def is_start_char(self, char): ...
    def get_tooltip(self, position): ...

class VariableScriptToken(DocumentedScriptToken):
    allowed_chars: Incomplete
    def is_start_char(self, char): ...
    def get_tooltip(self, position): ...

class UnicodeEscapeScriptToken(DocumentedScriptToken):
    allowed_chars: Incomplete
    unicode_escape_sequence: Incomplete
    def is_start_char(self, char): ...
    def is_allowed_char(self, char, position): ...
    def get_tooltip(self, position): ...

class ScriptTextEdit(QTextEdit):
    autocomplete_trigger_chars: Incomplete
    options: Incomplete
    highlighter: Incomplete
    wordwrap_action: Incomplete
    show_tooltips_action: Incomplete
    def __init__(self, parent) -> None: ...
    def contextMenuEvent(self, event) -> None: ...
    def mouseMoveEvent(self, event): ...
    def update_tooltip(self) -> None: ...
    def get_tooltip_at_mouse_position(self, position): ...
    def get_tooltip_at_cursor(self, cursor): ...
    def insertFromMimeData(self, source): ...
    def setPlainText(self, text) -> None: ...
    def update_wordwrap(self) -> None: ...
    def update_show_tooltips(self) -> None: ...
    completer: Incomplete
    popup_shown: bool
    def enable_completer(self) -> None: ...
    def insert_completion(self, completion) -> None: ...
    def popup_hide(self) -> None: ...
    def cursor_select_word(self, full_word: bool = True): ...
    def keyPressEvent(self, event) -> None: ...
    def handle_autocomplete(self, event) -> None: ...
