from PyQt5 import QtWidgets
from _typeshed import Incomplete
from picard.const import DEFAULT_SCRIPT_NAME as DEFAULT_SCRIPT_NAME
from picard.ui import HashableListWidgetItem as HashableListWidgetItem
from picard.util import unique_numbered_title as unique_numbered_title

class ScriptListWidget(QtWidgets.QListWidget):
    signal_reset_selected_item: Incomplete
    old_row: int
    bad_row: int
    def __init__(self, parent) -> None: ...
    def contextMenuEvent(self, event) -> None: ...
    def keyPressEvent(self, event) -> None: ...
    def unique_script_name(self): ...
    def add_script(self) -> None: ...
    def remove_selected_script(self) -> None: ...
    def remove_script(self, item) -> None: ...
    def item_changed(self, item) -> None: ...
    def current_item_changed(self, new_item, old_item) -> None: ...

class ScriptListWidgetItem(HashableListWidgetItem):
    script: Incomplete
    has_error: bool
    def __init__(
        self, name: Incomplete | None = None, enabled: bool = True, script: str = ""
    ) -> None: ...
    @property
    def pos(self): ...
    @property
    def name(self): ...
    @property
    def enabled(self): ...
    def get_all(self): ...
