from PyQt5 import QtWidgets
from _typeshed import Incomplete
from picard.ui.ui_widget_taglisteditor import Ui_TagListEditor as Ui_TagListEditor
from picard.ui.widgets.editablelistview import (
    AutocompleteItemDelegate as AutocompleteItemDelegate,
    EditableListModel as EditableListModel,
)
from picard.util.tags import TAG_NAMES as TAG_NAMES

class TagListEditor(QtWidgets.QWidget):
    ui: Incomplete
    def __init__(self, parent) -> None: ...
    def on_selection_changed(self, selected, deselected) -> None: ...
    def clear(self) -> None: ...
    def update(self, tags) -> None: ...
    @property
    def tags(self): ...
    def on_user_sortable_changed(self, user_sortable) -> None: ...
    def set_user_sortable(self, user_sortable) -> None: ...
