from _typeshed import Incomplete
from collections.abc import Generator
from enum import IntEnum
from picard import log as log
from picard.cluster import Cluster as Cluster
from picard.collection import (
    add_release_to_user_collections as add_release_to_user_collections,
)
from picard.config import get_config as get_config
from picard.const import VARIOUS_ARTISTS_ID as VARIOUS_ARTISTS_ID
from picard.dataobj import DataObject as DataObject
from picard.file import File as File
from picard.mbjson import (
    medium_to_metadata as medium_to_metadata,
    release_group_to_metadata as release_group_to_metadata,
    release_to_metadata as release_to_metadata,
    track_to_metadata as track_to_metadata,
)
from picard.metadata import (
    Metadata as Metadata,
    run_album_metadata_processors as run_album_metadata_processors,
    run_track_metadata_processors as run_track_metadata_processors,
)
from picard.plugin import (
    PluginFunctions as PluginFunctions,
    PluginPriority as PluginPriority,
)
from picard.script import (
    ScriptError as ScriptError,
    ScriptParser as ScriptParser,
    enabled_tagger_scripts_texts as enabled_tagger_scripts_texts,
)
from picard.track import Track as Track
from picard.ui.item import Item as Item
from picard.util import (
    find_best_match as find_best_match,
    format_time as format_time,
    mbid_validate as mbid_validate,
)
from picard.util.imagelist import (
    add_metadata_images as add_metadata_images,
    remove_metadata_images as remove_metadata_images,
    update_metadata_images as update_metadata_images,
)
from picard.util.textencoding import asciipunct as asciipunct

RECORDING_QUERY_LIMIT: int

class AlbumArtist(DataObject):
    def __init__(self, album_artist_id) -> None: ...

class AlbumStatus(IntEnum):
    NONE = 0
    LOADING = 1
    ERROR = 2
    LOADED = 3

class ParseResult(IntEnum):
    PARSED = 0
    REDIRECT = 1
    MISSING_TRACK_RELS = 2

class Album(DataObject, Item):
    metadata_images_changed: Incomplete
    metadata: Incomplete
    orig_metadata: Incomplete
    tracks: Incomplete
    loaded: bool
    load_task: Incomplete
    release_group: Incomplete
    unmatched_files: Incomplete
    status: Incomplete
    update_metadata_images_enabled: bool
    def __init__(self, album_id, discid: Incomplete | None = None) -> None: ...
    def iterfiles(self, save: bool = False) -> Generator[Incomplete, Incomplete]: ...
    def iter_correctly_matched_tracks(self) -> Generator[Incomplete, Incomplete]: ...
    def enable_update_metadata_images(self, enabled) -> None: ...
    def append_album_artist(self, album_artist_id): ...
    def add_discid(self, discid) -> None: ...
    def get_next_track(self, track): ...
    def get_album_artists(self): ...
    def load(self, priority: bool = False, refresh: bool = False) -> None: ...
    def run_when_loaded(self, func, always: bool = False) -> None: ...
    def stop_loading(self) -> None: ...
    def update(
        self, update_tracks: bool = True, update_selection: bool = True
    ) -> None: ...
    def add_file(self, track, file, new_album: bool = True) -> None: ...
    def remove_file(self, track, file, new_album: bool = True) -> None: ...
    def match_files(self, files) -> None: ...
    def can_save(self): ...
    def can_remove(self): ...
    def can_edit_tags(self): ...
    def can_analyze(self): ...
    def can_autotag(self): ...
    def can_refresh(self): ...
    def can_view_info(self): ...
    def is_album_like(self): ...
    def get_num_matched_tracks(self): ...
    def get_num_unmatched_files(self): ...
    def get_num_total_files(self): ...
    def is_complete(self): ...
    def is_modified(self): ...
    def get_num_unsaved_files(self): ...
    def column(self, column): ...
    id: Incomplete
    def switch_release_version(self, mbid) -> None: ...
    def update_metadata_images(self) -> None: ...
    def keep_original_images(self) -> None: ...

class NatAlbum(Album):
    loaded: bool
    def __init__(self) -> None: ...
    def update(
        self, update_tracks: bool = True, update_selection: bool = True
    ) -> None: ...
    def can_refresh(self): ...
    def can_browser_lookup(self): ...
    def can_view_info(self): ...

def register_album_post_removal_processor(function, priority=...) -> None: ...
def run_album_post_removal_processors(album_object) -> None: ...
