from _typeshed import Incomplete
from collections.abc import Generator

def setup_audit(prefixes_string): ...
def list_from_prefixes_string(prefixes_string) -> Generator[Incomplete, Incomplete]: ...
def make_prefixes_dict(prefixes_string): ...
def prefixes_candidates_for_length(
    length, prefixes_dict
) -> Generator[Incomplete, Incomplete]: ...
def is_matching_a_prefix(key, prefixes_dict): ...
