from PyQt5 import QtCore
from _typeshed import Incomplete
from collections.abc import Generator
from picard.config import get_config as get_config
from picard.file import File as File
from picard.metadata import Metadata as Metadata, SimMatchRelease as SimMatchRelease
from picard.track import Track as Track
from picard.ui.item import FileListItem as FileListItem, Item as Item
from picard.util import (
    album_artist_from_path as album_artist_from_path,
    find_best_match as find_best_match,
    format_time as format_time,
)
from picard.util.imagelist import (
    add_metadata_images as add_metadata_images,
    remove_metadata_images as remove_metadata_images,
    update_metadata_images as update_metadata_images,
)

class FileList(QtCore.QObject, FileListItem):
    metadata_images_changed: Incomplete
    metadata: Incomplete
    orig_metadata: Incomplete

    def __init__(self, files: Incomplete | None = None) -> None: ...
    def iterfiles(self, save: bool = False) -> Generator[Incomplete, Incomplete]: ...
    def update(self, signal: bool = True) -> None: ...
    @property
    def can_show_coverart(self): ...

class Cluster(FileList):
    comparison_weights: Incomplete
    item: Incomplete
    special: Incomplete
    hide_if_empty: Incomplete
    related_album: Incomplete
    lookup_task: Incomplete

    def __init__(
        self,
        name,
        artist: str = "",
        special: bool = False,
        related_album: Incomplete | None = None,
        hide_if_empty: bool = False,
    ) -> None: ...
    def __len__(self) -> int: ...
    @property
    def album(self): ...
    def add_files(self, files, new_album: bool = True) -> None: ...
    def add_file(self, file, new_album: bool = True) -> None: ...
    def remove_file(self, file, new_album: bool = True) -> None: ...
    def update(self, signal: bool = True) -> None: ...
    def get_num_files(self): ...
    def can_save(self): ...
    def can_remove(self): ...
    def can_edit_tags(self): ...
    def can_analyze(self): ...
    def can_autotag(self): ...
    def can_refresh(self): ...
    def can_browser_lookup(self): ...
    def can_view_info(self): ...
    def can_submit(self): ...
    def is_album_like(self): ...
    def column(self, column): ...
    def lookup_metadata(self) -> None: ...
    def clear_lookup_task(self) -> None: ...
    @staticmethod
    def cluster(files) -> Generator[Incomplete, Incomplete]: ...

class UnclusteredFiles(Cluster):
    def __init__(self) -> None: ...
    def add_files(self, files, new_album: bool = True) -> None: ...
    def remove_file(self, file, new_album: bool = True) -> None: ...
    def lookup_metadata(self) -> None: ...
    def can_edit_tags(self): ...
    def can_autotag(self): ...
    def can_view_info(self): ...
    def can_remove(self): ...
    @property
    def can_show_coverart(self): ...

class ClusterList(list, Item):
    def __init__(self) -> None: ...
    def __hash__(self): ...  # type: ignore[override]
    def __bool__(self) -> bool: ...
    def iterfiles(self, save: bool = False) -> Generator[Incomplete, Incomplete]: ...
    def can_save(self): ...
    def can_analyze(self): ...
    def can_autotag(self): ...
    def can_browser_lookup(self): ...
    def lookup_metadata(self) -> None: ...

class FileCluster:
    def __init__(self) -> None: ...
    def add(self, album, artist, file) -> None: ...
    @property
    def files(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def artist(self): ...
    @property
    def title(self): ...

def tokenize(word): ...
