from picard import log as log
from picard.config import (
    BoolOption as BoolOption,
    IntOption as IntOption,
    ListOption as ListOption,
    Option as Option,
    TextOption as TextOption,
)
from picard.const import (
    DEFAULT_FILE_NAMING_FORMAT as DEFAULT_FILE_NAMING_FORMAT,
    DEFAULT_SCRIPT_NAME as DEFAULT_SCRIPT_NAME,
)
from picard.const.sys import IS_FROZEN as IS_FROZEN
from picard.ui.options.renaming_compat import DEFAULT_REPLACEMENT as DEFAULT_REPLACEMENT
from picard.util import unique_numbered_title as unique_numbered_title

def upgrade_to_v1_0_0_final_0(
    config, interactive: bool = True, merge: bool = True
) -> None: ...
def upgrade_to_v1_3_0_dev_1(config) -> None: ...
def upgrade_to_v1_3_0_dev_2(config) -> None: ...
def upgrade_to_v1_3_0_dev_3(config) -> None: ...
def upgrade_to_v1_3_0_dev_4(config): ...
def upgrade_to_v1_4_0_dev_2(config) -> None: ...
def upgrade_to_v1_4_0_dev_3(config) -> None: ...

OLD_DEFAULT_FILE_NAMING_FORMAT_v1_3: str

def upgrade_to_v1_4_0_dev_4(config) -> None: ...
def upgrade_to_v1_4_0_dev_5(config) -> None: ...
def upgrade_to_v1_4_0_dev_6(config) -> None: ...
def upgrade_to_v1_4_0_dev_7(config) -> None: ...
def upgrade_to_v2_0_0_dev_3(config) -> None: ...
def upgrade_to_v2_1_0_dev_1(config) -> None: ...
def upgrade_to_v2_2_0_dev_3(config) -> None: ...

OLD_DEFAULT_FILE_NAMING_FORMAT_v2_1: str

def upgrade_to_v2_2_0_dev_4(config) -> None: ...
def upgrade_to_v2_4_0_beta_3(config) -> None: ...
def upgrade_to_v2_5_0_dev_1(config) -> None: ...
def upgrade_to_v2_5_0_dev_2(config) -> None: ...
def upgrade_to_v2_6_0_dev_1(config) -> None: ...
def upgrade_to_v2_6_0_beta_2(config) -> None: ...
def upgrade_to_v2_6_0_beta_3(config) -> None: ...
def upgrade_to_v2_7_0_dev_2(config) -> None: ...
def upgrade_to_v2_7_0_dev_3(config): ...
def upgrade_to_v2_7_0_dev_4(config) -> None: ...
def upgrade_to_v2_7_0_dev_5(config) -> None: ...
def upgrade_to_v2_8_0_dev_2(config) -> None: ...
def upgrade_to_v2_9_0_alpha_2(config) -> None: ...
def upgrade_to_v2_10_1_dev_2(config) -> None: ...
def upgrade_to_v2_12_3_dev_1(config) -> None: ...
def rename_option(config, old_opt, new_opt, option_type, default) -> None: ...
def upgrade_config(config) -> None: ...
