from PyQt5 import QtCore
from _typeshed import Incomplete
from collections.abc import Generator
from enum import Enum
from picard import PICARD_APP_NAME as PICARD_APP_NAME, log as log
from picard.config import get_config as get_config
from picard.const import DEFAULT_TIME_FORMAT as DEFAULT_TIME_FORMAT
from picard.const.sys import IS_MACOS as IS_MACOS, IS_WIN as IS_WIN
from picard.metadata import Metadata as Metadata, SimMatchTrack as SimMatchTrack
from picard.plugin import (
    PluginFunctions as PluginFunctions,
    PluginPriority as PluginPriority,
)
from picard.script import get_file_naming_script as get_file_naming_script
from picard.ui.item import Item as Item
from picard.util import (
    any_exception_isinstance as any_exception_isinstance,
    decode_filename as decode_filename,
    emptydir as emptydir,
    find_best_match as find_best_match,
    format_time as format_time,
    is_absolute_path as is_absolute_path,
    normpath as normpath,
    thread as thread,
    tracknum_and_title_from_filename as tracknum_and_title_from_filename,
)
from picard.util.filenaming import (
    get_available_filename as get_available_filename,
    make_save_path as make_save_path,
    make_short_filename as make_short_filename,
    move_ensure_casing as move_ensure_casing,
)
from picard.util.preservedtags import PreservedTags as PreservedTags
from picard.util.scripttofilename import (
    script_to_filename_with_metadata as script_to_filename_with_metadata,
)
from picard.util.tags import (
    CALCULATED_TAGS as CALCULATED_TAGS,
    PRESERVED_TAGS as PRESERVED_TAGS,
)

class FileErrorType(Enum):
    UNKNOWN = ...
    NOTFOUND = ...
    NOACCESS = ...
    PARSER = ...

class File(QtCore.QObject, Item):
    metadata_images_changed: Incomplete
    NAME: Incomplete
    UNDEFINED: int
    PENDING: int
    NORMAL: int
    CHANGED: int
    ERROR: int
    REMOVED: int
    LOOKUP_METADATA: int
    LOOKUP_ACOUSTID: int
    EXTENSIONS: Incomplete
    FILE_INFO_TAGS: Incomplete
    comparison_weights: Incomplete

    class PreserveTimesStatError(Exception): ...
    class PreserveTimesUtimeError(Exception): ...

    num_pending_files: int
    filename: Incomplete
    base_filename: Incomplete
    # state: Incomplete
    error_type: Incomplete
    orig_metadata: Incomplete
    metadata: Incomplete
    similarity: float
    parent: Incomplete
    lookup_task: Incomplete
    item: Incomplete
    acoustid_fingerprint: Incomplete
    acoustid_length: int
    match_recordingid: Incomplete

    def __init__(self, filename) -> None: ...
    def format_specific_metadata(
        self, metadata, tag, settings: Incomplete | None = None
    ): ...
    # For some reason this is genuinely overriden with a different signature
    def load(self, callback) -> None: ...  # type: ignore[override]
    def copy_metadata(self, metadata, preserve_deleted: bool = True) -> None: ...
    def keep_original_images(self) -> None: ...
    def has_error(self): ...
    def save(self) -> None: ...
    def make_filename(
        self,
        filename,
        metadata,
        settings: Incomplete | None = None,
        naming_format: Incomplete | None = None,
    ): ...
    def remove(self, from_parent: bool = True) -> None: ...
    def move(self, parent): ...
    def set_acoustid_fingerprint(
        self, fingerprint, length: Incomplete | None = None
    ) -> None: ...
    def acoustid_update(self) -> None: ...
    @classmethod
    def supports_tag(cls, name): ...
    def is_saved(self): ...
    def update(self, signal: bool = True) -> None: ...
    def can_save(self): ...
    def can_remove(self): ...
    def can_edit_tags(self): ...
    def can_analyze(self): ...
    def can_autotag(self): ...
    def can_refresh(self): ...
    def can_view_info(self): ...
    @property
    def state(self): ...
    @state.setter
    def state(self, state) -> None: ...
    def column(self, column): ...
    def lookup_metadata(self) -> None: ...
    def clear_lookup_task(self) -> None: ...
    def set_pending(self) -> None: ...
    def clear_pending(self, signal: bool = True) -> None: ...
    def update_item(self, update_selection: bool = True) -> None: ...
    def iterfiles(self, save: bool = False) -> Generator[Incomplete]: ...

def register_file_post_load_processor(function, priority=...) -> None: ...
def register_file_post_addition_to_track_processor(function, priority=...) -> None: ...
def register_file_post_removal_from_track_processor(function, priority=...) -> None: ...
def register_file_post_save_processor(function, priority=...) -> None: ...
def run_file_post_load_processors(file_object) -> None: ...
def run_file_post_addition_to_track_processors(track_object, file_object) -> None: ...
def run_file_post_removal_from_track_processors(track_object, file_object) -> None: ...
def run_file_post_save_processors(file_object) -> None: ...
