from _typeshed import Incomplete
from picard import log as log
from picard.config import get_config as get_config
from picard.const import (
    ALIAS_TYPE_ARTIST_NAME_ID as ALIAS_TYPE_ARTIST_NAME_ID,
    ALIAS_TYPE_LEGAL_NAME_ID as ALIAS_TYPE_LEGAL_NAME_ID,
    RELEASE_FORMATS as RELEASE_FORMATS,
)
from picard.util import (
    format_time as format_time,
    linear_combination_of_weights as linear_combination_of_weights,
    parse_amazon_url as parse_amazon_url,
    translate_from_sortname as translate_from_sortname,
)
from picard.util.script_detector_weighted import (
    detect_script_weighted as detect_script_weighted,
)
from types import SimpleNamespace

class RelFunc(SimpleNamespace):
    clear_metadata_first: bool
    func: Incomplete

def artist_credit_from_node(node): ...
def artist_credit_to_metadata(node, m, release: bool = False) -> None: ...
def countries_from_node(node): ...
def release_dates_and_countries_from_node(node): ...
def label_info_from_node(node): ...
def media_formats_from_node(node): ...
def track_to_metadata(node, track) -> None: ...
def recording_to_metadata(node, m, track: Incomplete | None = None) -> None: ...
def work_to_metadata(work, m, instrumental: bool = False) -> None: ...
def medium_to_metadata(node, m) -> None: ...
def artist_to_metadata(node, m) -> None: ...
def release_to_metadata(node, m, album: Incomplete | None = None) -> None: ...
def release_group_to_metadata(
    node, m, release_group: Incomplete | None = None
) -> None: ...
def add_secondary_release_types(node, m) -> None: ...
def add_genres_from_node(node, obj) -> None: ...
def add_genres(node, obj) -> None: ...
def add_user_genres(node, obj) -> None: ...
def add_isrcs_to_metadata(node, metadata) -> None: ...
def get_score(node): ...
