from _typeshed import Incomplete
from picard import log as log
from picard.config import get_config as get_config
from picard.const import (
    MUSICBRAINZ_OAUTH_CLIENT_ID as MUSICBRAINZ_OAUTH_CLIENT_ID,
    MUSICBRAINZ_OAUTH_CLIENT_SECRET as MUSICBRAINZ_OAUTH_CLIENT_SECRET,
)
from picard.util import build_qurl as build_qurl, load_json as load_json

OOB_URI: str

class OAuthInvalidStateError(Exception): ...

class OAuthManager:
    webservice: Incomplete
    def __init__(self, webservice) -> None: ...
    @property
    def redirect_uri(self): ...
    @redirect_uri.setter
    def redirect_uri(self, redirect_uri) -> None: ...
    @property
    def is_oob(self): ...
    @property
    def setting(self): ...
    @property
    def persist(self): ...
    @property
    def host(self): ...
    @property
    def port(self): ...
    @property
    def refresh_token(self): ...
    @refresh_token.setter
    def refresh_token(self, value) -> None: ...
    @refresh_token.deleter
    def refresh_token(self) -> None: ...
    @property
    def refresh_token_scopes(self): ...
    @refresh_token_scopes.setter
    def refresh_token_scopes(self, value) -> None: ...
    @refresh_token_scopes.deleter
    def refresh_token_scopes(self) -> None: ...
    @property
    def access_token(self): ...
    @access_token.setter
    def access_token(self, value) -> None: ...
    @access_token.deleter
    def access_token(self) -> None: ...
    @property
    def access_token_expires(self): ...
    @access_token_expires.setter
    def access_token_expires(self, value) -> None: ...
    @access_token_expires.deleter
    def access_token_expires(self) -> None: ...
    @property
    def username(self): ...
    @username.setter
    def username(self, value) -> None: ...
    def is_authorized(self): ...
    def is_logged_in(self): ...
    def revoke_tokens(self, callback) -> None: ...
    def forget_refresh_token(self) -> None: ...
    def forget_access_token(self) -> None: ...
    def get_access_token(self, callback) -> None: ...
    def url(self, path: Incomplete | None = None, params: Incomplete | None = None): ...
    def verify_state(self, state): ...
    def get_authorization_url(self, scopes, callback: callable): ...
    def set_refresh_token(self, refresh_token, scopes) -> None: ...
    def set_access_token(self, access_token, expires_in) -> None: ...
    def refresh_access_token(self, callback) -> None: ...
    def on_refresh_access_token_finished(self, callback, data, http, error) -> None: ...
    def exchange_authorization_code(
        self, authorization_code, scopes, callback
    ) -> None: ...
    def on_exchange_authorization_code_finished(
        self, scopes, callback, data, http, error
    ) -> None: ...
    def fetch_username(self, callback) -> None: ...
    def on_fetch_username_finished(self, callback, data, http, error) -> None: ...

def s256_encode(input: bytes) -> bytes: ...
def base64url_encode(input: bytes) -> bytes: ...
