from _typeshed import Incomplete
from picard import log as log
from picard.config import get_config as get_config
from picard.const import USER_PLUGIN_DIR as USER_PLUGIN_DIR
from picard.version import Version as Version, VersionError as VersionError

class ExtensionPoint:
    label: Incomplete
    def __init__(self, label: Incomplete | None = None) -> None: ...
    def register(self, module, item) -> None: ...
    def unregister_module(self, name) -> None: ...
    def __iter__(self): ...

class PluginShared:
    def __init__(self) -> None: ...

class PluginWrapper(PluginShared):
    module: Incomplete
    compatible: bool
    dir: Incomplete
    data: Incomplete
    def __init__(
        self,
        module,
        plugindir,
        file: Incomplete | None = None,
        manifest_data: Incomplete | None = None,
    ) -> None: ...
    @property
    def name(self): ...
    @property
    def module_name(self): ...
    @property
    def author(self): ...
    @property
    def description(self): ...
    @property
    def version(self): ...
    @property
    def api_versions(self): ...
    @property
    def file(self): ...
    @property
    def license(self): ...
    @property
    def license_url(self): ...
    @property
    def user_guide_url(self): ...
    @property
    def files_list(self): ...
    @property
    def is_user_installed(self): ...

class PluginData(PluginShared):
    __dict__: Incomplete
    module_name: Incomplete
    def __init__(self, d, module_name) -> None: ...
    def __getattribute__(self, name): ...
    @property
    def version(self): ...
    @property
    def files_list(self): ...

class PluginPriority:
    HIGH: int
    NORMAL: int
    LOW: int

class PluginFunctions:
    functions: Incomplete
    def __init__(self, label: Incomplete | None = None) -> None: ...
    def register(self, module, item, priority=...) -> None: ...
    def run(self, *args, **kwargs): ...
