from PyQt5 import QtCore
from _typeshed import Incomplete
from collections.abc import Generator
from importlib.abc import MetaPathFinder
from picard import log as log
from picard.const import PLUGINS_API as PLUGINS_API, USER_PLUGIN_DIR as USER_PLUGIN_DIR
from picard.const.sys import IS_FROZEN as IS_FROZEN
from picard.plugin import PluginData as PluginData, PluginWrapper as PluginWrapper
from picard.version import Version as Version, VersionError as VersionError

def is_update(path): ...
def strip_update_suffix(path): ...
def is_zip(path): ...
def strip_zip_suffix(path): ...
def is_package(path): ...
def strip_package_suffix(path): ...
def is_zipped_package(path): ...
def load_zip_manifest(archive_path): ...
def zip_import(path): ...
def plugin_dirs() -> Generator[Incomplete, Incomplete]: ...
def init_default_plugin_dirs() -> None: ...
def register_plugin_dir(path) -> None: ...
def plugin_dir_for_path(path): ...

class PluginManager(QtCore.QObject):
    plugin_installed: Incomplete
    plugin_updated: Incomplete
    plugin_removed: Incomplete
    plugin_errored: Incomplete
    updates_available: Incomplete
    plugins: Incomplete
    plugins_directory: Incomplete
    def __init__(self, plugins_directory: Incomplete | None = None) -> None: ...
    @property
    def available_plugins(self): ...
    def plugin_error(self, name, error, *args, **kwargs) -> None: ...
    def handle_plugin_updates(self) -> None: ...
    def load_plugins_from_directory(self, plugindir) -> None: ...
    def remove_plugin(self, plugin_name, with_update: bool = False) -> None: ...
    def install_plugin(
        self,
        path,
        update: bool = False,
        plugin_name: Incomplete | None = None,
        plugin_data: Incomplete | None = None,
    ) -> None: ...
    def query_available_plugins(self, callback: Incomplete | None = None) -> None: ...
    def is_available(self, plugin_name): ...
    def enabled(self, name): ...
    def check_update(self) -> None: ...

class PluginMetaPathFinder(MetaPathFinder):
    def find_spec(self, fullname, path, target: Incomplete | None = None): ...
