import argparse
from PyQt5 import QtWidgets
from _typeshed import Incomplete
from collections.abc import Generator
from picard import (
    PICARD_APP_ID as PICARD_APP_ID,
    PICARD_APP_NAME as PICARD_APP_NAME,
    PICARD_DESKTOP_NAME as PICARD_DESKTOP_NAME,
    PICARD_FANCY_VERSION_STR as PICARD_FANCY_VERSION_STR,
    PICARD_ORG_NAME as PICARD_ORG_NAME,
    acoustid as acoustid,
    log as log,
)
from picard.acoustid.manager import AcoustIDManager as AcoustIDManager
from picard.album import (
    Album as Album,
    NatAlbum as NatAlbum,
    run_album_post_removal_processors as run_album_post_removal_processors,
)
from picard.audit import setup_audit as setup_audit
from picard.browser.browser import BrowserIntegration as BrowserIntegration
from picard.browser.filelookup import FileLookup as FileLookup
from picard.cluster import (
    Cluster as Cluster,
    ClusterList as ClusterList,
    UnclusteredFiles as UnclusteredFiles,
)
from picard.collection import load_user_collections as load_user_collections
from picard.config import get_config as get_config, setup_config as setup_config
from picard.config_upgrade import upgrade_config as upgrade_config
from picard.const import USER_DIR as USER_DIR
from picard.const.sys import (
    IS_HAIKU as IS_HAIKU,
    IS_MACOS as IS_MACOS,
    IS_WIN as IS_WIN,
)
from picard.dataobj import DataObject as DataObject
from picard.disc import (
    Disc as Disc,
    dbpoweramplog as dbpoweramplog,
    eaclog as eaclog,
    whipperlog as whipperlog,
)
from picard.file import File as File
from picard.i18n import setup_gettext as setup_gettext
from picard.pluginmanager import (
    PluginManager as PluginManager,
    plugin_dirs as plugin_dirs,
)
from picard.releasegroup import ReleaseGroup as ReleaseGroup
from picard.track import NonAlbumTrack as NonAlbumTrack, Track as Track
from picard.ui import FONT_FAMILY_MONOSPACE as FONT_FAMILY_MONOSPACE, theme as theme
from picard.ui.mainwindow import MainWindow as MainWindow
from picard.ui.searchdialog.album import AlbumSearchDialog as AlbumSearchDialog
from picard.ui.searchdialog.artist import ArtistSearchDialog as ArtistSearchDialog
from picard.ui.searchdialog.track import TrackSearchDialog as TrackSearchDialog
from picard.util import (
    check_io_encoding as check_io_encoding,
    encode_filename as encode_filename,
    is_hidden as is_hidden,
    iter_files_from_objects as iter_files_from_objects,
    mbid_validate as mbid_validate,
    normpath as normpath,
    periodictouch as periodictouch,
    pipe as pipe,
    process_events_iter as process_events_iter,
    system_supports_long_paths as system_supports_long_paths,
    thread as thread,
    versions as versions,
    webbrowser2 as webbrowser2,
)
from picard.util.cdrom import (
    DISCID_NOT_LOADED_MESSAGE as DISCID_NOT_LOADED_MESSAGE,
    get_cdrom_drives as get_cdrom_drives,
)
from picard.util.checkupdate import UpdateCheckManager as UpdateCheckManager
from picard.util.remotecommands import (
    REMOTE_COMMANDS as REMOTE_COMMANDS,
    RemoteCommands as RemoteCommands,
)
from picard.webservice import WebService as WebService
from picard.webservice.api_helpers import (
    AcoustIdAPIHelper as AcoustIdAPIHelper,
    MBAPIHelper as MBAPIHelper,
)

class ParseItemsToLoad:
    WINDOWS_DRIVE_TEST: Incomplete
    files: Incomplete
    mbids: Incomplete
    urls: Incomplete
    def __init__(self, items) -> None: ...
    def non_executable_items(self): ...
    def __bool__(self) -> bool: ...

class Tagger(QtWidgets.QApplication):
    tagger_stats_changed: Incomplete
    listen_port_changed: Incomplete
    cluster_added: Incomplete
    cluster_removed: Incomplete
    album_added: Incomplete
    album_removed: Incomplete
    browser_integration: Incomplete
    exit_cleanup: Incomplete
    pipe_handler: Incomplete
    priority_thread_pool: Incomplete
    save_thread_pool: Incomplete
    stopping: bool
    thread_pool: Incomplete
    webservice: Incomplete
    autoupdate_enabled: Incomplete
    signalfd: Incomplete
    signalnotifier: Incomplete
    mb_api: Incomplete
    acoustidmanager: Incomplete
    pluginmanager: Incomplete
    files: Incomplete
    clusters: Incomplete
    albums: Incomplete
    release_groups: Incomplete
    mbid_redirects: Incomplete
    unclustered_files: Incomplete
    nats: Incomplete
    window: Incomplete
    updatecheckmanager: Incomplete
    def __init__(
        self, picard_args, localedir, autoupdate, pipe_handler: Incomplete | None = None
    ) -> None: ...
    @property
    def is_wayland(self): ...
    def pipe_server(self) -> None: ...
    def start_process_commands(self) -> None: ...
    def run_commands(self) -> None: ...
    def load_to_picard(self, items) -> None: ...
    def iter_album_files(self) -> Generator[Incomplete, Incomplete]: ...
    def iter_all_files(self) -> Generator[Incomplete, Incomplete]: ...
    def handle_command_clear_logs(self, argstring) -> None: ...
    def handle_command_cluster(self, argstring) -> None: ...
    def handle_command_fingerprint(self, argstring) -> None: ...
    def handle_command_from_file(self, argstring) -> None: ...
    def handle_command_load(self, argstring) -> None: ...
    def handle_command_lookup(self, argstring) -> None: ...
    def handle_command_lookup_cd(self, argstring) -> None: ...
    def handle_command_pause(self, argstring) -> None: ...
    def handle_command_quit(self, argstring) -> None: ...
    def handle_command_remove(self, argstring) -> None: ...
    def handle_command_remove_all(self, argstring) -> None: ...
    def handle_command_remove_empty(self, argstring) -> None: ...
    def handle_command_remove_saved(self, argstring) -> None: ...
    def handle_command_remove_unclustered(self, argstring) -> None: ...
    def handle_command_save_matched(self, argstring) -> None: ...
    def handle_command_save_modified(self, argstring) -> None: ...
    def handle_command_scan(self, argstring) -> None: ...
    def handle_command_show(self, argstring) -> None: ...
    def handle_command_submit_fingerprints(self, argstring) -> None: ...
    def handle_command_write_logs(self, argstring) -> None: ...
    def enable_menu_icons(self, enabled) -> None: ...
    def register_cleanup(self, func) -> None: ...
    def run_cleanup(self) -> None: ...
    def set_log_level(self, level) -> None: ...
    def on_listen_port_changed(self, port) -> None: ...
    def mb_login(self, callback, parent: Incomplete | None = None) -> None: ...
    def on_mb_authorization_finished(
        self, callback, successful: bool = False, error_msg: Incomplete | None = None
    ) -> None: ...
    def on_mb_login_finished(self, callback, successful, error_msg) -> None: ...
    def mb_logout(self, callback) -> None: ...
    def on_mb_logout_finished(self, callback, successful, error_msg) -> None: ...
    def move_files_to_album(
        self, files, albumid: Incomplete | None = None, album: Incomplete | None = None
    ) -> None: ...
    def move_file_to_album(self, file, albumid) -> None: ...
    def move_file_to_track(self, file, albumid, recordingid) -> None: ...
    def create_nats(self): ...
    def move_file_to_nat(
        self, file, recordingid, node: Incomplete | None = None
    ) -> None: ...
    def quit(self) -> None: ...
    def exit(self) -> None: ...
    def run(self): ...
    def update_browser_integration(self) -> None: ...
    def event(self, event): ...
    def move_file(self, file, target): ...
    def move_files(self, files, target, move_to_multi_tracks: bool = True) -> None: ...
    def add_files(self, filenames, target: Incomplete | None = None): ...
    def add_paths(self, paths, target: Incomplete | None = None) -> None: ...
    def get_file_lookup(self): ...
    def search(
        self,
        text,
        search_type,
        adv: bool = False,
        mbid_matched_callback: Incomplete | None = None,
        force_browser: bool = False,
    ) -> None: ...
    def collection_lookup(self) -> None: ...
    def browser_lookup(self, item) -> None: ...
    def get_files_from_objects(self, objects, save: bool = False): ...
    def save(self, objects) -> None: ...
    def load_mbid(self, type, mbid) -> None: ...
    def load_album(self, album_id, discid: Incomplete | None = None): ...
    def load_nat(self, nat_id, node: Incomplete | None = None): ...
    def get_nat_by_id(self, nat_id): ...
    def get_release_group_by_id(self, rg_id): ...
    def remove_files(self, files, from_parent: bool = True) -> None: ...
    def remove_album(self, album) -> None: ...
    def remove_nat(self, track) -> None: ...
    def remove_cluster(self, cluster) -> None: ...
    def remove(self, objects) -> None: ...
    def lookup_cd(self, action): ...
    def lookup_discid_from_logfile(self) -> None: ...
    @property
    def use_acoustid(self): ...
    def analyze(self, objs) -> None: ...
    def generate_fingerprints(self, objs) -> None: ...
    def autotag(self, objects) -> None: ...
    def cluster(self, objs, callback: Incomplete | None = None) -> None: ...
    def load_cluster(self, name, artist): ...
    def set_wait_cursor(self) -> None: ...
    def restore_cursor(self) -> None: ...
    def refresh(self, objs) -> None: ...
    def bring_tagger_front(self) -> None: ...
    @classmethod
    def instance(cls): ...
    def signal(self, signum, frame) -> None: ...
    def sighandler(self) -> None: ...

class PicardArgumentParser(argparse.ArgumentParser):
    def exit(self, status: int = 0, message: Incomplete | None = None) -> None: ...
    def error(self, message) -> None: ...
    def print_help(self, file: Incomplete | None = None): ...

def is_windowed_app(): ...
def show_standalone_messagebox(
    message, informative_text: Incomplete | None = None
) -> None: ...
def print_message_and_exit(
    message, informative_text: Incomplete | None = None, status: int = 0
) -> None: ...
def print_help_for_commands() -> None: ...
def process_picard_args(): ...
def main(localedir: Incomplete | None = None, autoupdate: bool = True) -> None: ...
