from _typeshed import Incomplete
from collections import Counter
from collections.abc import Generator
from picard import log as log
from picard.config import get_config as get_config
from picard.const import (
    DATA_TRACK_TITLE as DATA_TRACK_TITLE,
    SILENCE_TRACK_TITLE as SILENCE_TRACK_TITLE,
    VARIOUS_ARTISTS_ID as VARIOUS_ARTISTS_ID,
)
from picard.dataobj import DataObject as DataObject
from picard.file import (
    run_file_post_addition_to_track_processors as run_file_post_addition_to_track_processors,
    run_file_post_removal_from_track_processors as run_file_post_removal_from_track_processors,
)
from picard.mbjson import recording_to_metadata as recording_to_metadata
from picard.metadata import (
    Metadata as Metadata,
    MultiMetadataProxy as MultiMetadataProxy,
    run_track_metadata_processors as run_track_metadata_processors,
)
from picard.script import (
    ScriptError as ScriptError,
    ScriptParser as ScriptParser,
    enabled_tagger_scripts_texts as enabled_tagger_scripts_texts,
)
from picard.ui.item import FileListItem as FileListItem
from picard.util import pattern_as_regex as pattern_as_regex, titlecase as titlecase
from picard.util.imagelist import (
    ImageList as ImageList,
    add_metadata_images as add_metadata_images,
    remove_metadata_images as remove_metadata_images,
)
from picard.util.textencoding import asciipunct as asciipunct

class TagGenreFilter:
    errors: Incomplete
    match_regexes: Incomplete
    def __init__(self, filters) -> None: ...
    def skip(self, tag): ...
    def filter(self, counter: Counter, minusage: int = 0) -> Counter: ...
    def format_errors(self) -> Generator[Incomplete]: ...

class TrackArtist(DataObject):
    def __init__(self, ta_id) -> None: ...

class Track(DataObject, FileListItem):
    metadata_images_changed: Incomplete
    metadata: Incomplete
    orig_metadata: Incomplete
    album: Incomplete
    scripted_metadata: Incomplete
    def __init__(self, track_id, album: Incomplete | None = None) -> None: ...
    @property
    def num_linked_files(self): ...
    @property
    def linked_files(self): ...
    def add_file(self, file, new_album: bool = True) -> None: ...
    def update_file_metadata(self, file) -> None: ...
    def remove_file(self, file, new_album: bool = True) -> None: ...
    @staticmethod
    def run_scripts(metadata, strip_whitespace: bool = False) -> None: ...
    def update(self) -> None: ...
    def is_linked(self): ...
    def can_save(self): ...
    def can_remove(self): ...
    def can_edit_tags(self): ...
    def can_view_info(self): ...
    @property
    def can_link_fingerprint(self): ...
    def column(self, column): ...
    def is_video(self): ...
    def is_pregap(self): ...
    def is_data(self): ...
    def is_silence(self): ...
    def is_complete(self): ...
    def ignored_for_completeness(self): ...
    def append_track_artist(self, ta_id): ...

class NonAlbumTrack(Track):
    callback: Incomplete
    loaded: bool
    status: Incomplete
    def __init__(self, nat_id) -> None: ...
    def can_refresh(self): ...
    def column(self, column): ...
    def load(self, priority: bool = False, refresh: bool = False) -> None: ...
    def can_remove(self): ...
    def run_when_loaded(self, func) -> None: ...
