from _typeshed import Incomplete
from typing import NamedTuple

class VersionError(Exception): ...

class Version(
    NamedTuple(
        "VersionBase",
        [
            ("major", Incomplete),
            ("minor", Incomplete),
            ("patch", Incomplete),
            ("identifier", Incomplete),
            ("revision", Incomplete),
        ],
    )
):
    def __new__(
        cls,
        major,
        minor: int = 0,
        patch: int = 0,
        identifier: str = "final",
        revision: int = 0,
    ): ...
    @classmethod
    def from_string(cls, version_str): ...
    @classmethod
    def valid_identifiers(cls): ...
    def to_string(self, short: bool = False): ...
    @property
    def sortkey(self): ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...
