from picard import log as log
from picard.util import format_time as format_time
from picard.util.mbserver import build_submission_url as build_submission_url
from picard.util.webbrowser2 import open as open

class InvalidTokenError(Exception): ...
class NotFoundError(Exception): ...

def is_available(): ...
def is_enabled(): ...
def submit_cluster(cluster) -> None: ...
def submit_file(file, as_release: bool = False) -> None: ...
def serve_form(token): ...
def extract_discnumber(metadata): ...
