from _typeshed import Incomplete
from picard import log as log
from picard.config import get_config as get_config
from picard.const import PICARD_URLS as PICARD_URLS
from picard.disc import Disc as Disc
from picard.ui.searchdialog.album import AlbumSearchDialog as AlbumSearchDialog
from picard.util import build_qurl as build_qurl, webbrowser2 as webbrowser2

class FileLookup:
    RE_MB_ENTITY: Incomplete
    RE_MB_CDTOC: Incomplete
    server: Incomplete
    local_port: Incomplete
    port: Incomplete
    def __init__(self, parent, server, port, local_port) -> None: ...
    def launch(self, url): ...
    def recording_lookup(self, recording_id): ...
    def album_lookup(self, album_id): ...
    def artist_lookup(self, artist_id): ...
    def track_lookup(self, track_id): ...
    def work_lookup(self, work_id): ...
    def release_group_lookup(self, release_group_id): ...
    def discid_lookup(self, discid): ...
    def discid_submission(self, url): ...
    def acoust_lookup(self, acoust_id): ...
    def mbid_lookup(
        self,
        string,
        type_: Incomplete | None = None,
        mbid_matched_callback: Incomplete | None = None,
        browser_fallback: bool = True,
    ): ...
    def tag_lookup(self, artist, release, track, tracknum, duration, filename): ...
    def collection_lookup(self, userid): ...
    def search_entity(
        self,
        type_,
        query,
        adv: bool = False,
        mbid_matched_callback: Incomplete | None = None,
        force_browser: bool = False,
    ): ...
