from _typeshed import Incomplete
from picard.ui.options import OptionsPage as OptionsPage

class ProviderOptions(OptionsPage):
    PARENT: str
    ui: Incomplete
    def __init__(self, parent: Incomplete | None = None) -> None: ...

class CoverArtProviderMetaClass(type):
    @property
    def name(cls): ...
    @property
    def title(cls): ...

class CoverArtProvider(metaclass=CoverArtProviderMetaClass):
    FINISHED: int
    WAIT: int
    coverart: Incomplete
    release: Incomplete
    metadata: Incomplete
    album: Incomplete
    def __init__(self, coverart) -> None: ...
    def enabled(self): ...
    def queue_images(self) -> None: ...
    def error(self, msg) -> None: ...
    def queue_put(self, what) -> None: ...
    def next_in_queue(self) -> None: ...
    def match_url_relations(self, relation_types, func) -> None: ...
