from _typeshed import Incomplete
from picard import PICARD_VERSION_STR as PICARD_VERSION_STR
from picard.config import get_config as get_config
from picard.const import (
    ACOUSTID_KEY as ACOUSTID_KEY,
    ACOUSTID_URL as ACOUSTID_URL,
    MUSICBRAINZ_SERVERS as MUSICBRAINZ_SERVERS,
)
from picard.util import encoded_queryargs as encoded_queryargs
from picard.webservice import CLIENT_STRING as CLIENT_STRING, ratecontrol as ratecontrol
from picard.webservice.utils import host_port_to_url as host_port_to_url

def escape_lucene_query(text): ...
def build_lucene_query(args): ...

class APIHelper:
    def __init__(self, webservice, base_url: Incomplete | None = None) -> None: ...
    @property
    def base_url(self): ...
    @base_url.setter
    def base_url(self, url) -> None: ...
    @property
    def webservice(self): ...
    def url_from_path(self, path): ...
    def get(self, path, handler, **kwargs): ...
    def post(self, path, data, handler, **kwargs): ...
    def put(self, path, data, handler, **kwargs): ...
    def delete(self, path, handler, **kwargs): ...

class MBAPIHelper(APIHelper):
    @property
    def base_url(self): ...
    def get_release_by_id(
        self, releaseid, handler, inc: Incomplete | None = None, **kwargs
    ): ...
    def get_track_by_id(
        self, trackid, handler, inc: Incomplete | None = None, **kwargs
    ): ...
    def lookup_discid(
        self,
        discid,
        handler,
        priority: bool = True,
        important: bool = True,
        refresh: bool = False,
    ): ...
    def find_releases(self, handler, **kwargs): ...
    def find_tracks(self, handler, **kwargs): ...
    def find_artists(self, handler, **kwargs): ...
    def browse_releases(self, handler, **kwargs): ...
    def browse_recordings(self, handler, inc, **kwargs): ...
    def submit_ratings(self, ratings, handler): ...
    def get_collection(
        self, collection_id, handler, limit: int = 100, offset: int = 0
    ): ...
    def get_collection_list(self, handler): ...
    def put_to_collection(self, collection_id, releases, handler) -> None: ...
    def delete_from_collection(self, collection_id, releases, handler) -> None: ...

class AcoustIdAPIHelper(APIHelper):
    client_key = ACOUSTID_KEY
    client_version = PICARD_VERSION_STR
    def __init__(self, webservice) -> None: ...
    def query_acoustid(self, handler, **args): ...
    def submit_acoustid_fingerprints(self, submissions, handler): ...
