from _typeshed import Incomplete
from picard import log as log
from picard.webservice.utils import hostkey_from_url as hostkey_from_url

REQUEST_DELAY_MINIMUM: Incomplete
REQUEST_DELAY: Incomplete
REQUEST_DELAY_EXPONENT: Incomplete
CONGESTION_UNACK: Incomplete
CONGESTION_WINDOW_SIZE: Incomplete
CONGESTION_SSTHRESH: Incomplete
LAST_REQUEST_TIMES: Incomplete

def set_minimum_delay(hostkey, delay_ms) -> None: ...
def set_minimum_delay_for_url(url, delay_ms) -> None: ...
def current_delay(hostkey): ...
def get_delay_to_next_request(hostkey): ...
def increment_requests(hostkey) -> None: ...
def decrement_requests(hostkey) -> None: ...
def copy_minimal_delay(from_hostkey, to_hostkey) -> None: ...
def adjust(hostkey, slow_down) -> None: ...
