from _typeshed import Incomplete
from picard.const.countries import RELEASE_COUNTRIES as RELEASE_COUNTRIES
from picard.metadata import MULTI_VALUED_JOINER as MULTI_VALUED_JOINER
from picard.script.parser import (
    MultiValue as MultiValue,
    ScriptParser as ScriptParser,
    ScriptRuntimeError as ScriptRuntimeError,
    normalize_tagname as normalize_tagname,
)
from picard.util import (
    pattern_as_regex as pattern_as_regex,
    titlecase as titlecase,
    uniqify as uniqify,
)
from typing import NamedTuple

class Bound(NamedTuple):
    lower: Incomplete
    upper: Incomplete

class FunctionRegistryItem:
    function: Incomplete
    eval_args: Incomplete
    argcount: Incomplete
    documentation: Incomplete
    name: Incomplete
    module: Incomplete
    def __init__(
        self,
        function,
        eval_args,
        argcount,
        documentation: Incomplete | None = None,
        name: Incomplete | None = None,
        module: Incomplete | None = None,
    ) -> None: ...
    def markdowndoc(self, postprocessor: Incomplete | None = None): ...
    def htmldoc(self, postprocessor: Incomplete | None = None): ...

def register_script_function(
    function,
    name: Incomplete | None = None,
    eval_args: bool = True,
    check_argcount: bool = True,
    documentation: Incomplete | None = None,
) -> None: ...
def script_function(
    name: Incomplete | None = None,
    eval_args: bool = True,
    check_argcount: bool = True,
    prefix: str = "func_",
    documentation: Incomplete | None = None,
): ...
def func_if(parser, _if, _then, _else: Incomplete | None = None): ...
def func_if2(parser, *args): ...
def func_noop(parser, *args): ...
def func_left(parser, text, length): ...
def func_right(parser, text, length): ...
def func_lower(parser, text): ...
def func_upper(parser, text): ...
def func_pad(parser, text, length, char): ...
def func_strip(parser, text): ...
def func_replace(parser, text, old, new): ...
def func_replacemulti(parser, multi, search, replace, separator=...): ...
def func_in(parser, text, needle): ...
def func_inmulti(parser, haystack, needle, separator=...): ...
def func_rreplace(parser, text, old, new): ...
def func_rsearch(parser, text, pattern): ...
def func_num(parser, text, length): ...
def func_unset(parser, name): ...
def func_delete(parser, name): ...
def func_set(parser, name, value): ...
def func_setmulti(parser, name, value, separator=...): ...
def func_get(parser, name): ...
def func_copy(parser, new, old): ...
def func_copymerge(parser, new, old, keep_duplicates: bool = False): ...
def func_trim(parser, text, char: Incomplete | None = None): ...
def func_add(parser, x, y, *args): ...
def func_sub(parser, x, y, *args): ...
def func_div(parser, x, y, *args): ...
def func_mod(parser, x, y, *args): ...
def func_mul(parser, x, y, *args): ...
def func_or(parser, x, y, *args): ...
def func_and(parser, x, y, *args): ...
def func_not(parser, x): ...
def func_eq(parser, x, y): ...
def func_ne(parser, x, y): ...
def func_lt(parser, x, y, _type: Incomplete | None = None): ...
def func_lte(parser, x, y, _type: Incomplete | None = None): ...
def func_gt(parser, x, y, _type: Incomplete | None = None): ...
def func_gte(parser, x, y, _type: Incomplete | None = None): ...
def func_len(parser, text: str = ""): ...
def func_lenmulti(parser, multi, separator=...): ...
def func_performer(parser, pattern: str = "", join: str = ", "): ...
def func_matchedtracks(parser, *args): ...
def func_is_complete(parser): ...
def func_firstalphachar(parser, text: str = "", nonalpha: str = "#"): ...
def func_initials(parser, text: str = ""): ...
def func_firstwords(parser, text, length): ...
def func_startswith(parser, text, prefix): ...
def func_endswith(parser, text, suffix): ...
def func_truncate(parser, text, length): ...
def func_swapprefix(parser, text, *prefixes): ...
def func_delprefix(parser, text, *prefixes): ...
def func_eq_any(parser, x, *args): ...
def func_ne_all(parser, x, *args): ...
def func_eq_all(parser, x, *args): ...
def func_ne_any(parser, x, *args): ...
def func_title(parser, text): ...
def func_is_audio(parser): ...
def func_is_video(parser): ...
def func_find(parser, haystack, needle): ...
def func_reverse(parser, text): ...
def func_substr(parser, text, start_index, end_index: Incomplete | None = None): ...
def func_getmulti(parser, multi, item_index, separator=...): ...
def func_foreach(parser, multi, loop_code, separator=...): ...
def func_while(parser, condition, loop_code): ...
def func_map(parser, multi, loop_code, separator=...): ...
def func_join(parser, multi, join_phrase, separator=...): ...
def func_slice(
    parser, multi, start_index, end_index: Incomplete | None = None, separator=...
): ...
def func_datetime(parser, format: Incomplete | None = None): ...
def func_sortmulti(parser, multi, separator=...): ...
def func_reversemulti(parser, multi, separator=...): ...
def func_unique(parser, multi, case_sensitive: str = "", separator=...): ...
def func_countryname(parser, country_code, translate: str = ""): ...

class DateTuple(NamedTuple):
    year: Incomplete
    month: Incomplete
    day: Incomplete

def func_year(parser, date_to_parse, date_order: str = "ymd"): ...
def func_month(parser, date_to_parse, date_order: str = "ymd"): ...
def func_day(parser, date_to_parse, date_order: str = "ymd"): ...
def func_dateformat(
    parser,
    date_to_parse,
    date_format: Incomplete | None = None,
    date_order: str = "ymd",
): ...
def func_is_multi(parser, multi): ...
def func_cleanmulti(parser, multi): ...
def func_min(parser, _type, x, *args): ...
def func_max(parser, _type, x, *args): ...
