from _typeshed import Incomplete
from collections.abc import MutableSequence
from picard.metadata import (
    MULTI_VALUED_JOINER as MULTI_VALUED_JOINER,
    Metadata as Metadata,
)
from picard.plugin import ExtensionPoint as ExtensionPoint

class ScriptError(Exception): ...

class ScriptParseError(ScriptError):
    def __init__(self, stackitem, message) -> None: ...

class ScriptEndOfFile(ScriptParseError):
    def __init__(self, stackitem) -> None: ...

class ScriptSyntaxError(ScriptParseError): ...
class ScriptUnicodeError(ScriptSyntaxError): ...

class ScriptUnknownFunction(ScriptParseError):
    def __init__(self, stackitem) -> None: ...

class ScriptRuntimeError(ScriptError):
    def __init__(self, stackitem, message: str = "Unknown error") -> None: ...

class StackItem:
    line: Incomplete
    column: Incomplete
    name: Incomplete
    def __init__(self, line, column, name: Incomplete | None = None) -> None: ...

class ScriptText(str):
    def eval(self, state): ...

def normalize_tagname(name): ...

class ScriptVariable:
    name: Incomplete
    def __init__(self, name) -> None: ...
    def eval(self, state): ...

class ScriptFunction:
    stackitem: Incomplete
    name: Incomplete
    args: Incomplete
    def __init__(self, name, args, parser, column: int = 0, line: int = 0) -> None: ...
    def eval(self, parser): ...

class ScriptExpression(list):
    def eval(self, state): ...

def isidentif(ch): ...

class ScriptParser:
    def __init__(self) -> None: ...
    def read(self): ...
    def read_multi(self, count): ...
    def unread(self) -> None: ...
    def parse_arguments(self): ...
    def parse_function(self): ...
    def parse_variable(self): ...
    def parse_text(self, top): ...
    def parse_escape_sequence(self): ...
    def parse_expression(self, top): ...
    functions: Incomplete
    def load_functions(self) -> None: ...
    def parse(self, script, functions: bool = False): ...
    context: Incomplete
    file: Incomplete
    def eval(
        self, script, context: Incomplete | None = None, file: Incomplete | None = None
    ): ...

class MultiValue(MutableSequence):
    parser: Incomplete
    separator: Incomplete
    def __init__(self, parser, multi, separator) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def insert(self, index, value): ...
