from PyQt5 import QtWidgets
from _typeshed import Incomplete
from picard import log as log
from picard.config import Option as Option, get_config as get_config
from picard.const import CAA_URL as CAA_URL
from picard.mbjson import (
    countries_from_node as countries_from_node,
    media_formats_from_node as media_formats_from_node,
    release_group_to_metadata as release_group_to_metadata,
    release_to_metadata as release_to_metadata,
)
from picard.metadata import Metadata as Metadata
from picard.ui.searchdialog import Retry as Retry, SearchDialog as SearchDialog
from picard.util import countries_shortlist as countries_shortlist
from picard.webservice.api_helpers import build_lucene_query as build_lucene_query

class CoverWidget(QtWidgets.QWidget):
    shown: Incomplete
    layout: Incomplete
    loading_gif_label: Incomplete
    def __init__(self, parent, width: int = 100, height: int = 100) -> None: ...
    def set_pixmap(self, pixmap) -> None: ...
    def not_found(self) -> None: ...
    def sizeHint(self): ...
    def showEvent(self, event) -> None: ...
    def invalidate(self) -> None: ...

class CoverCell:
    release: Incomplete
    fetched: bool
    fetch_task: Incomplete
    widget: Incomplete
    def __init__(
        self, table, release, row, column, on_show: Incomplete | None = None
    ) -> None: ...
    def is_visible(self): ...
    def set_pixmap(self, pixmap) -> None: ...
    def not_found(self) -> None: ...
    def invalidate(self) -> None: ...

class AlbumSearchDialog(SearchDialog):
    dialog_header_state: str
    options: Incomplete
    cluster: Incomplete
    existing_album: Incomplete
    columns: Incomplete
    cover_cells: Incomplete
    fetching: bool
    def __init__(
        self,
        parent,
        force_advanced_search: Incomplete | None = None,
        existing_album: Incomplete | None = None,
    ) -> None: ...
    @staticmethod
    def show_releasegroup_search(
        releasegroup_id, existing_album: Incomplete | None = None
    ): ...
    retry_params: Incomplete
    def search(self, text) -> None: ...
    def show_similar_albums(self, cluster) -> None: ...
    def retry(self) -> None: ...
    def handle_reply(self, document, http, error) -> None: ...
    def fetch_coverarts(self) -> None: ...
    def fetch_coverart(self, cell) -> None: ...
    def fetch_cleanup(self) -> None: ...
    def closeEvent(self, event) -> None: ...
    def parse_releases(self, releases) -> None: ...
    def display_results(self) -> None: ...
    def accept_event(self, rows) -> None: ...
    def load_selection(self, row) -> None: ...
