from _typeshed import Incomplete
from picard.config import Option as Option, get_config as get_config
from picard.mbjson import artist_to_metadata as artist_to_metadata
from picard.metadata import Metadata as Metadata
from picard.ui.searchdialog import Retry as Retry, SearchDialog as SearchDialog

class ArtistSearchDialog(SearchDialog):
    dialog_header_state: str
    options: Incomplete
    columns: Incomplete
    def __init__(self, parent) -> None: ...
    retry_params: Incomplete
    def search(self, text) -> None: ...
    def retry(self) -> None: ...
    def handle_reply(self, document, http, error) -> None: ...
    def parse_artists(self, artists) -> None: ...
    def display_results(self) -> None: ...
    def accept_event(self, rows) -> None: ...
    def load_in_browser(self, row) -> None: ...
