from picard import log as log
from picard.plugin import ExtensionPoint as ExtensionPoint

def register_format(file_format) -> None: ...
def supported_formats(): ...
def supported_extensions(): ...
def ext_to_format(ext): ...
def guess_format(filename, options=...): ...
def open_(filename): ...
