from _typeshed import Incomplete
from collections.abc import MutableMapping
from picard import log as log
from picard.config import get_config as get_config
from picard.file import File as File
from picard.formats.id3 import NonCompatID3File as NonCompatID3File
from picard.metadata import Metadata as Metadata

TRANSLATE_RIFF_INFO: Incomplete
R_TRANSLATE_RIFF_INFO: Incomplete

def translate_tag_to_riff_name(name): ...

class RiffListInfo(MutableMapping):
    encoding: Incomplete
    def __init__(self, encoding: str = "windows-1252") -> None: ...
    def load(self, filething) -> None: ...
    def save(self, filething) -> None: ...
    def delete(self, filething) -> None: ...
    def __contains__(self, name) -> bool: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...

class WAVFile(NonCompatID3File):
    EXTENSIONS: Incomplete
    NAME: str

class WAVFile(File):
    EXTENSIONS: Incomplete
    NAME: str
    @classmethod
    def supports_tag(cls, name): ...
