from PyQt5 import QtCore
from _typeshed import Incomplete
from picard import log as log
from picard.util import load_json as load_json

FINGERPRINT_MAX_ALLOWED_LENGTH_DIFF_MS: int

class Submission:
    fingerprint: Incomplete
    duration: Incomplete
    recordingid: Incomplete
    metadata: Incomplete
    attempts: int
    def __init__(
        self,
        fingerprint,
        duration,
        recordingid: Incomplete | None = None,
        metadata: Incomplete | None = None,
    ) -> None: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    @property
    def puid(self): ...
    @property
    def valid_duration(self): ...
    @property
    def is_submitted(self): ...
    @property
    def args(self): ...

class AcoustIDManager(QtCore.QObject):
    MAX_PAYLOAD: int
    MAX_ATTEMPTS: int
    BATCH_SIZE_REDUCTION_FACTOR: float
    def __init__(self, acoustid_api) -> None: ...
    def add(self, file, recordingid) -> None: ...
    def update(self, file, recordingid) -> None: ...
    def remove(self, file) -> None: ...
    def is_submitted(self, file): ...
    max_batch_size: Incomplete
    def submit(self) -> None: ...
