from _typeshed import Incomplete
from collections.abc import Generator
from picard.config import (
    BoolOption as BoolOption,
    ListOption as ListOption,
    TextOption as TextOption,
    get_config as get_config,
)
from picard.const.locales import ALIAS_LOCALES as ALIAS_LOCALES
from picard.const.scripts import (
    SCRIPTS as SCRIPTS,
    scripts_sorted_by_localized_name as scripts_sorted_by_localized_name,
)
from picard.ui import PicardDialog as PicardDialog
from picard.ui.moveable_list_view import MoveableListView as MoveableListView
from picard.ui.options import (
    OptionsPage as OptionsPage,
    register_options_page as register_options_page,
)
from picard.ui.ui_exception_script_selector import (
    Ui_ExceptionScriptSelector as Ui_ExceptionScriptSelector,
)
from picard.ui.ui_multi_locale_selector import (
    Ui_MultiLocaleSelector as Ui_MultiLocaleSelector,
)
from picard.ui.ui_options_metadata import (
    Ui_MetadataOptionsPage as Ui_MetadataOptionsPage,
)
from picard.ui.util import qlistwidget_items as qlistwidget_items

def iter_sorted_locales(locales) -> Generator[Incomplete]: ...

class MetadataOptionsPage(OptionsPage):
    NAME: str
    TITLE: Incomplete
    PARENT: Incomplete
    SORT_ORDER: int
    ACTIVE: bool
    HELP_URL: str
    options: Incomplete
    ui: Incomplete
    def __init__(self, parent: Incomplete | None = None) -> None: ...
    current_locales: Incomplete
    current_scripts: Incomplete
    def load(self) -> None: ...
    def make_locales_text(self) -> None: ...
    def make_scripts_text(self) -> None: ...
    def save(self) -> None: ...
    def set_va_name_default(self) -> None: ...
    def set_nat_name_default(self) -> None: ...
    def set_enabled_states(self) -> None: ...
    def open_locale_selector(self) -> None: ...
    def open_script_selector(self) -> None: ...

class MultiLocaleSelector(PicardDialog):
    ui: Incomplete
    move_view: Incomplete
    def __init__(self, parent: Incomplete | None = None) -> None: ...
    def load(self): ...
    def add_locale(self) -> None: ...
    def remove_locale(self) -> None: ...
    def set_button_state(self) -> None: ...
    def save_changes(self) -> None: ...

class ScriptExceptionSelector(PicardDialog):
    ui: Incomplete
    move_view: Incomplete
    def __init__(self, parent: Incomplete | None = None) -> None: ...
    @staticmethod
    def make_label(script_id, script_weighting): ...
    def load(self) -> None: ...
    def add_script(self) -> None: ...
    def remove_script(self) -> None: ...
    def selected_script_changed(self) -> None: ...
    def weighting_changed(self) -> None: ...
    def set_button_state(self) -> None: ...
    def set_weighting_selector(self) -> None: ...
    def set_item_from_weighting(self) -> None: ...
    def save_changes(self) -> None: ...
