from PyQt5 import QtWidgets
from _typeshed import Incomplete
from collections.abc import Generator
from picard import log as log
from picard.config import (
    ListOption as ListOption,
    Option as Option,
    get_config as get_config,
)
from picard.const import PLUGINS_API as PLUGINS_API, USER_PLUGIN_DIR as USER_PLUGIN_DIR
from picard.ui import HashableTreeWidgetItem as HashableTreeWidgetItem
from picard.ui.options import (
    OptionsPage as OptionsPage,
    register_options_page as register_options_page,
)
from picard.ui.theme import theme as theme
from picard.ui.ui_options_plugins import Ui_PluginsOptionsPage as Ui_PluginsOptionsPage
from picard.util import (
    icontheme as icontheme,
    open_local_path as open_local_path,
    reconnect as reconnect,
)

COLUMN_NAME: Incomplete
COLUMN_VERSION: Incomplete
COLUMN_ACTIONS: Incomplete

class PluginActionButton(QtWidgets.QToolButton):
    switch_method: Incomplete
    def __init__(
        self,
        icon: Incomplete | None = None,
        tooltip: Incomplete | None = None,
        retain_space: bool = False,
        switch_method: Incomplete | None = None,
        *args,
        **kwargs,
    ) -> None: ...
    def mode(self, mode) -> None: ...
    def setIcon(self, icon) -> None: ...

class PluginTreeWidgetItem(HashableTreeWidgetItem):
    upgrade_to_version: Incomplete
    new_version: Incomplete
    is_enabled: bool
    is_installed: bool
    installed_font: Incomplete
    enabled_font: Incomplete
    available_font: Incomplete
    buttons: Incomplete
    buttons_widget: Incomplete
    def __init__(self, icons, *args, **kwargs) -> None: ...
    def show_install(self, button, mode) -> None: ...
    def show_update(self, button, mode) -> None: ...
    def show_enable(self, button, mode) -> None: ...
    def show_uninstall(self, button, mode) -> None: ...
    def save_state(self): ...
    def restore_state(self, states) -> None: ...
    def __lt__(self, other): ...
    def sortData(self, column): ...
    def setSortData(self, column, data) -> None: ...
    @property
    def plugin(self): ...
    def enable(self, boolean, greyout: Incomplete | None = None) -> None: ...

class PluginsOptionsPage(OptionsPage):
    NAME: str
    TITLE: Incomplete
    PARENT: Incomplete
    SORT_ORDER: int
    ACTIVE: bool
    HELP_URL: str
    options: Incomplete
    ui: Incomplete
    manager: Incomplete
    icons: Incomplete
    def __init__(self, parent: Incomplete | None = None) -> None: ...
    def create_icon(self, icon_name): ...
    def items(self) -> Generator[Incomplete]: ...
    def find_item_by_plugin_name(self, plugin_name): ...
    def selected_item(self): ...
    def save_state(self) -> None: ...
    def set_current_item(self, item, scroll: bool = False) -> None: ...
    def restore_state(self) -> None: ...
    @staticmethod
    def is_plugin_enabled(plugin): ...
    def available_plugins_name_version(self): ...
    def installable_plugins(self) -> Generator[Incomplete]: ...
    def installed_plugins(self): ...
    def enabled_plugins(self): ...
    def restore_defaults(self) -> None: ...
    def load(self) -> None: ...
    def reload_list_of_plugins(self) -> None: ...
    def plugin_loading_error(self, plugin_name, error) -> None: ...
    def plugin_installed(self, plugin) -> None: ...
    def plugin_updated(self, plugin_name) -> None: ...
    def plugin_removed(self, plugin_name) -> None: ...
    def uninstall_plugin(self, item) -> None: ...
    def update_plugin_item(
        self,
        item,
        plugin,
        make_current: bool = False,
        enabled: Incomplete | None = None,
        new_version: Incomplete | None = None,
        is_installed: Incomplete | None = None,
    ): ...
    def save(self) -> None: ...
    def refresh_details(self, item) -> None: ...
    @staticmethod
    def link_authors(authors): ...
    @staticmethod
    def link_user_guide(user_guide): ...
    def change_details(self) -> None: ...
    def open_plugins(self) -> None: ...
    def download_plugin(self, item, update: bool = False) -> None: ...
    def download_handler(self, update, response, reply, error, plugin) -> None: ...
    @staticmethod
    def open_plugin_dir() -> None: ...
    def mimeTypes(self): ...
    def dragEnterEvent(self, event) -> None: ...
    def dragMoveEvent(self, event) -> None: ...
    def dropEvent(self, event) -> None: ...
