from _typeshed import Incomplete
from collections.abc import Generator
from picard.config import (
    IntOption as IntOption,
    ListOption as ListOption,
    SettingConfigSection as SettingConfigSection,
    get_config as get_config,
)
from picard.const import DEFAULT_COPY_TEXT as DEFAULT_COPY_TEXT
from picard.profile import UserProfileGroups as UserProfileGroups
from picard.script import (
    get_file_naming_script_presets as get_file_naming_script_presets,
)
from picard.ui.moveable_list_view import MoveableListView as MoveableListView
from picard.ui.options import (
    OptionsPage as OptionsPage,
    register_options_page as register_options_page,
)
from picard.ui.ui_options_profiles import (
    Ui_ProfileEditorDialog as Ui_ProfileEditorDialog,
)
from picard.ui.util import qlistwidget_items as qlistwidget_items
from picard.ui.widgets.profilelistwidget import (
    ProfileListWidgetItem as ProfileListWidgetItem,
)
from picard.util import get_base_title as get_base_title

class ProfilesOptionsPage(OptionsPage):
    NAME: str
    TITLE: Incomplete
    PARENT: Incomplete
    SORT_ORDER: int
    ACTIVE: bool
    HELP_URL: str
    PROFILES_KEY: Incomplete
    SETTINGS_KEY: Incomplete
    POSITION_KEY: str
    EXPANDED_KEY: str
    TREEWIDGETITEM_COLUMN: int
    options: Incomplete
    signal_refresh: Incomplete
    ui: Incomplete
    move_view: Incomplete
    current_profile_id: Incomplete
    expanded_sections: Incomplete
    building_tree: bool
    loading: bool
    settings_changed: bool
    def __init__(self, parent: Incomplete | None = None) -> None: ...
    def eventFilter(self, object, event): ...
    new_profile_button: Incomplete
    copy_profile_button: Incomplete
    delete_profile_button: Incomplete
    def make_buttons(self) -> None: ...
    profile_settings: Incomplete
    def restore_defaults(self) -> None: ...
    def load(self) -> None: ...
    def update_config_overrides(self, reset: bool = False) -> None: ...
    def get_settings_for_profile(self, profile_id): ...
    def make_setting_tree(self, settings: Incomplete | None = None) -> None: ...
    def make_setting_value_text(self, key, value): ...
    def update_current_expanded_items_list(self) -> None: ...
    def get_current_selected_item(self): ...
    def profile_selected(self, update_settings: bool = True) -> None: ...
    def reload_all_page_settings(self) -> None: ...
    def update_values_in_profile_options(self) -> None: ...
    def profile_item_changed(self, item) -> None: ...
    def current_item_changed(self, new_item, old_item) -> None: ...
    def get_checked_items_from_tree(self) -> Generator[Incomplete]: ...
    def set_profile_settings_changed(self) -> None: ...
    def copy_profile(self) -> None: ...
    def new_profile(self) -> None: ...
    def delete_profile(self) -> None: ...
    def save(self) -> None: ...
    def set_button_states(self) -> None: ...
