from _typeshed import Incomplete
from picard.config import ListOption as ListOption, get_config as get_config
from picard.const import (
    RELEASE_FORMATS as RELEASE_FORMATS,
    RELEASE_PRIMARY_GROUPS as RELEASE_PRIMARY_GROUPS,
    RELEASE_SECONDARY_GROUPS as RELEASE_SECONDARY_GROUPS,
)
from picard.const.countries import RELEASE_COUNTRIES as RELEASE_COUNTRIES
from picard.const.sys import IS_WIN as IS_WIN
from picard.i18n import sort_key as sort_key
from picard.ui.options import (
    OptionsPage as OptionsPage,
    register_options_page as register_options_page,
)
from picard.ui.ui_options_releases import (
    Ui_ReleasesOptionsPage as Ui_ReleasesOptionsPage,
)
from picard.ui.util import qlistwidget_items as qlistwidget_items
from picard.ui.widgets import ClickableSlider as ClickableSlider

class TipSlider(ClickableSlider):
    style: Incomplete
    opt: Incomplete
    def __init__(self, *args) -> None: ...
    def showEvent(self, event) -> None: ...
    def hideEvent(self, event) -> None: ...
    def show_tip(self, value) -> None: ...
    def round_value(self, value) -> None: ...

class ReleaseTypeScore:
    group: Incomplete
    layout: Incomplete
    label: Incomplete
    slider: Incomplete
    def __init__(self, group, layout, label, cell) -> None: ...
    def setValue(self, value) -> None: ...
    def value(self): ...
    def reset(self) -> None: ...

class RowColIter:
    step: Incomplete
    cols: Incomplete
    rows: Incomplete
    current: Incomplete
    def __init__(self, max_cells, max_cols: int = 6, step: int = 2) -> None: ...
    def __iter__(self): ...
    def __next__(self): ...

class ReleasesOptionsPage(OptionsPage):
    NAME: str
    TITLE: Incomplete
    PARENT: str
    SORT_ORDER: int
    ACTIVE: bool
    HELP_URL: str
    options: Incomplete
    ui: Incomplete
    def __init__(self, parent: Incomplete | None = None) -> None: ...
    def restore_defaults(self) -> None: ...
    def load(self) -> None: ...
    def save(self) -> None: ...
    def reset_preferred_types(self) -> None: ...
    def add_preferred_countries(self) -> None: ...
    def remove_preferred_countries(self) -> None: ...
    def add_preferred_formats(self) -> None: ...
    def remove_preferred_formats(self) -> None: ...
