from _typeshed import Incomplete
from picard.config import (
    BoolOption as BoolOption,
    TextOption as TextOption,
    get_config as get_config,
)
from picard.script import ScriptParser as ScriptParser
from picard.ui.options import (
    OptionsCheckError as OptionsCheckError,
    OptionsPage as OptionsPage,
    register_options_page as register_options_page,
)
from picard.ui.options.scripting import (
    ScriptCheckError as ScriptCheckError,
    ScriptingDocumentationDialog as ScriptingDocumentationDialog,
)
from picard.ui.scripteditor import (
    ScriptEditorDialog as ScriptEditorDialog,
    ScriptEditorExamples as ScriptEditorExamples,
    populate_script_selection_combo_box as populate_script_selection_combo_box,
    synchronize_vertical_scrollbars as synchronize_vertical_scrollbars,
)
from picard.ui.ui_options_renaming import (
    Ui_RenamingOptionsPage as Ui_RenamingOptionsPage,
)

class RenamingOptionsPage(OptionsPage):
    NAME: str
    TITLE: Incomplete
    PARENT: Incomplete
    SORT_ORDER: int
    ACTIVE: bool
    HELP_URL: str
    options: Incomplete
    script_text: str
    compat_options: Incomplete
    ui: Incomplete
    script_palette_normal: Incomplete
    script_palette_readonly: Incomplete
    examples: Incomplete
    script_editor_dialog: Incomplete
    current_row: int
    def __init__(self, parent: Incomplete | None = None) -> None: ...
    naming_scripts: Incomplete
    selected_naming_script_id: Incomplete
    def update_selector_from_editor(self) -> None: ...
    def update_selector_from_settings(self) -> None: ...
    def update_selector_in_editor(self) -> None: ...
    def match_after_to_before(self) -> None: ...
    def match_before_to_after(self) -> None: ...
    def show_script_editing_page(self) -> None: ...
    def script_editor_dialog_close(self) -> None: ...
    def show_scripting_documentation(self) -> None: ...
    def toggle_file_naming_format(self, state) -> None: ...
    def save_from_editor(self) -> None: ...
    def check_formats(self) -> None: ...
    def update_example_files(self) -> None: ...
    def update_examples_from_local(self) -> None: ...
    def update_displayed_examples(self) -> None: ...
    def display_examples(self) -> None: ...
    def load(self) -> None: ...
    def on_compat_options_changed(self, options) -> None: ...
    def check(self) -> None: ...
    def check_format(self) -> None: ...
    def save(self) -> None: ...
    def display_error(self, error) -> None: ...
    def move_files_to_browse(self) -> None: ...
    def test(self) -> None: ...
