from PyQt5 import QtWidgets
from _typeshed import Incomplete
from picard import log as log
from picard.config import Option as Option, get_config as get_config
from picard.const import DOCS_BASE_URL as DOCS_BASE_URL
from picard.const.sys import (
    IS_HAIKU as IS_HAIKU,
    IS_MACOS as IS_MACOS,
    IS_WIN as IS_WIN,
)
from picard.util import restore_method as restore_method, webbrowser2 as webbrowser2

FONT_FAMILY_MONOSPACE: str

class PreserveGeometry:
    defaultsize: Incomplete
    def __init__(self) -> None: ...
    def opt_name(self): ...
    def splitters_name(self): ...
    def restore_geometry(self) -> None: ...
    def save_geometry(self) -> None: ...

class SingletonDialog:
    @classmethod
    def get_instance(cls, *args, **kwargs): ...
    @classmethod
    def show_instance(cls, *args, **kwargs): ...

class PicardDialog(QtWidgets.QDialog, PreserveGeometry):
    help_url: Incomplete
    flags: Incomplete
    ready_for_display: Incomplete
    def __init__(self, parent: Incomplete | None = None) -> None: ...
    def keyPressEvent(self, event) -> None: ...
    def showEvent(self, event): ...
    def show_help(self) -> None: ...

class HashableTreeWidgetItem(QtWidgets.QTreeWidgetItem):
    id: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...

class HashableListWidgetItem(QtWidgets.QListWidgetItem):
    id: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
