from PyQt5 import QtWidgets
from _typeshed import Incomplete
from picard.collection import (
    load_user_collections as load_user_collections,
    user_collections as user_collections,
)
from picard.i18n import sort_key as sort_key

class CollectionMenu(QtWidgets.QMenu):
    ids: Incomplete
    def __init__(self, albums, *args) -> None: ...
    actions: Incomplete
    refresh_action: Incomplete
    def update_collections(self): ...
    def refresh_list(self) -> None: ...
    def mouseReleaseEvent(self, event) -> None: ...
    def update_highlight(self, action) -> None: ...
    def update_active_action_for_widget(self, widget) -> None: ...

class CollectionMenuItem(QtWidgets.QWidget):
    menu: Incomplete
    active: bool
    def __init__(self, menu, collection) -> None: ...
    def set_active(self, active) -> None: ...
    def enterEvent(self, e) -> None: ...
    def leaveEvent(self, e) -> None: ...
    def paintEvent(self, e) -> None: ...

class CollectionCheckBox(QtWidgets.QCheckBox):
    menu: Incomplete
    collection: Incomplete
    def __init__(self, parent, menu, collection) -> None: ...
    def nextCheckState(self) -> None: ...
    def updateText(self) -> None: ...
    def label(self): ...
