from _typeshed import Incomplete
from picard.config import get_config as get_config
from picard.ui.theme import theme as theme

class UnknownColorException(Exception): ...

class DefaultColor:
    value: Incomplete
    description: Incomplete
    def __init__(self, value, description) -> None: ...

def register_color(themes, name, value) -> None: ...

class InterfaceColors:
    def __init__(self, dark_theme: Incomplete | None = None) -> None: ...
    @property
    def dark_theme(self): ...
    @property
    def default_colors(self): ...
    def set_default_colors(self) -> None: ...
    def set_colors(self, colors_dict) -> None: ...
    def load_from_config(self) -> None: ...
    def get_colors(self): ...
    def get_color(self, color_key): ...
    def get_qcolor(self, color_key): ...
    def get_color_description(self, color_key): ...
    def set_color(self, color_key, color_value) -> None: ...
    def save_to_config(self): ...

interface_colors: Incomplete
