from PyQt5 import QtWidgets
from _typeshed import Incomplete
from collections.abc import Generator
from picard import log as log
from picard.album import Album as Album
from picard.cluster import Cluster as Cluster
from picard.config import get_config as get_config
from picard.const import MAX_COVERS_TO_STACK as MAX_COVERS_TO_STACK
from picard.coverart.image import (
    CoverArtImage as CoverArtImage,
    CoverArtImageError as CoverArtImageError,
    CoverArtImageIOError as CoverArtImageIOError,
)
from picard.file import File as File
from picard.track import Track as Track
from picard.ui.item import FileListItem as FileListItem
from picard.ui.widgets import ActiveLabel as ActiveLabel
from picard.util import imageinfo as imageinfo, normpath as normpath
from picard.util.lrucache import LRUCache as LRUCache

THUMBNAIL_WIDTH: int
COVERART_WIDTH: Incomplete

class CoverArtThumbnail(ActiveLabel):
    image_dropped: Incomplete
    data: Incomplete
    has_common_images: Incomplete
    release: Incomplete
    pixel_ratio: Incomplete
    related_images: Incomplete
    current_pixmap_key: Incomplete
    def __init__(
        self,
        active: bool = False,
        drops: bool = False,
        pixmap_cache: Incomplete | None = None,
        *args,
        **kwargs,
    ) -> None: ...
    def screen_changed(self, screen) -> None: ...
    def __eq__(self, other): ...
    def dragEnterEvent(self, event) -> None: ...
    def dropEvent(self, event) -> None: ...
    def scaled(self, *dimensions): ...
    def show(self) -> None: ...
    def set_data(self, data, force: bool = False, has_common_images: bool = True): ...
    def decorate_cover(self, pixmap): ...
    def render_cover_stack(self, data, has_common_images): ...
    def set_metadata(self, metadata) -> None: ...
    def open_release_page(self) -> None: ...

def set_image_replace(obj, coverartimage) -> None: ...
def set_image_append(obj, coverartimage) -> None: ...
def iter_file_parents(file) -> Generator[Incomplete]: ...

HTML_IMG_SRC_REGEX: Incomplete

class CoverArtBox(QtWidgets.QGroupBox):
    layout: Incomplete
    parent: Incomplete
    item: Incomplete
    pixmap_cache: Incomplete
    cover_art_label: Incomplete
    cover_art: Incomplete
    orig_cover_art_label: Incomplete
    orig_cover_art: Incomplete
    show_details_button: Incomplete
    def __init__(self, parent) -> None: ...
    def show_cover_art_info(self) -> None: ...
    def update_display(self, force: bool = False) -> None: ...
    def set_item(self, item) -> None: ...
    def update_metadata(self) -> None: ...
    def fetch_remote_image(
        self, url, fallback_data: Incomplete | None = None
    ) -> None: ...
    def on_remote_image_fetched(
        self, url, data, reply, error, fallback_data: Incomplete | None = None
    ) -> None: ...
    def load_remote_image(self, url, data) -> None: ...
    def choose_local_file(self) -> None: ...
    def set_load_image_behavior(self, behavior) -> None: ...
    def keep_original_images(self) -> None: ...
    def contextMenuEvent(self, event) -> None: ...
