from PyQt5 import QtWidgets
from _typeshed import Incomplete
from picard.const import (
    RELEASE_FORMATS as RELEASE_FORMATS,
    RELEASE_PRIMARY_GROUPS as RELEASE_PRIMARY_GROUPS,
    RELEASE_SECONDARY_GROUPS as RELEASE_SECONDARY_GROUPS,
    RELEASE_STATUS as RELEASE_STATUS,
)
from picard.const.countries import RELEASE_COUNTRIES as RELEASE_COUNTRIES
from picard.ui import PicardDialog as PicardDialog
from picard.ui.ui_edittagdialog import Ui_EditTagDialog as Ui_EditTagDialog
from picard.util.tags import TAG_NAMES as TAG_NAMES

AUTOCOMPLETE_RELEASE_TYPES: Incomplete
AUTOCOMPLETE_RELEASE_STATUS: Incomplete
AUTOCOMPLETE_RELEASE_COUNTRIES: Incomplete
AUTOCOMPLETE_RELEASE_FORMATS: Incomplete

class TagEditorDelegate(QtWidgets.QItemDelegate):
    def createEditor(self, parent, option, index): ...
    def get_tag_name(self, index): ...

class EditTagDialog(PicardDialog):
    ui: Incomplete
    window: Incomplete
    value_list: Incomplete
    metadata_box: Incomplete
    tag: Incomplete
    modified_tags: Incomplete
    different: bool
    default_tags: Incomplete
    completer: Incomplete
    def __init__(self, window, tag) -> None: ...
    def keyPressEvent(self, event) -> None: ...
    def tag_selected(self, index) -> None: ...
    def edit_value(self) -> None: ...
    def add_value(self) -> None: ...
    def add_or_edit_value(self) -> None: ...
    def remove_value(self) -> None: ...
    def on_rows_inserted(self, parent, first, last) -> None: ...
    def on_rows_removed(self, parent, first, last) -> None: ...
    def move_row_up(self) -> None: ...
    def move_row_down(self) -> None: ...
    def disable_all(self) -> None: ...
    def enable_all(self) -> None: ...
    def tag_changed(self, tag) -> None: ...
    def value_edited(self, item) -> None: ...
    def value_selection_changed(self) -> None: ...
    def accept(self) -> None: ...
