from PyQt5 import QtWidgets
from _typeshed import Incomplete
from picard import log as log
from picard.config import (
    BoolOption as BoolOption,
    TextOption as TextOption,
    get_config as get_config,
)
from picard.const.sys import IS_MACOS as IS_MACOS
from picard.formats import supported_formats as supported_formats
from picard.util import find_existing_path as find_existing_path

class FileBrowser(QtWidgets.QTreeView):
    options: Incomplete
    load_selected_files_action: Incomplete
    move_files_here_action: Incomplete
    toggle_hidden_action: Incomplete
    set_as_starting_directory_action: Incomplete
    focused: bool
    def __init__(self, parent) -> None: ...
    def showEvent(self, event) -> None: ...
    def contextMenuEvent(self, event) -> None: ...
    def scrollTo(self, index, scrolltype=...) -> None: ...
    def mousePressEvent(self, event) -> None: ...
    def focusInEvent(self, event) -> None: ...
    def show_hidden(self, state) -> None: ...
    def save_state(self) -> None: ...
    def restore_state(self) -> None: ...
    def load_file_for_item(self, index) -> None: ...
    def load_selected_files(self) -> None: ...
    def move_files_here(self) -> None: ...
    def set_as_starting_directory(self) -> None: ...
