from PyQt5 import QtWidgets
from picard.ui.ui_infostatus import Ui_InfoStatus as Ui_InfoStatus
from picard.util import icontheme as icontheme
from picard.util.time import get_timestamp as get_timestamp

class InfoStatus(QtWidgets.QWidget, Ui_InfoStatus):
    def __init__(self, parent) -> None: ...
    def update(
        self,
        files: int = 0,
        albums: int = 0,
        pending_files: int = 0,
        pending_requests: int = 0,
        progress: int = 0,
    ) -> None: ...
    def reset_counters(self) -> None: ...
    def get_progress(self): ...
    def set_eta(self, eta_seconds) -> None: ...
    def hide_eta(self) -> None: ...
    def set_files(self, num) -> None: ...
    def set_albums(self, num) -> None: ...
    def set_pending_files(self, num) -> None: ...
    def set_pending_requests(self, num) -> None: ...
