from _typeshed import Incomplete
from collections.abc import Generator
from picard import log as log
from picard.util.imagelist import update_metadata_images as update_metadata_images

class Item:
    def can_save(self): ...
    def can_remove(self): ...
    def can_edit_tags(self): ...
    def can_analyze(self): ...
    def can_autotag(self): ...
    def can_refresh(self): ...
    def can_view_info(self): ...
    def can_submit(self): ...
    @property
    def can_show_coverart(self): ...
    def can_browser_lookup(self): ...
    def is_album_like(self): ...
    @property
    def can_link_fingerprint(self): ...
    def load(self, priority: bool = False, refresh: bool = False) -> None: ...
    @property
    def tracknumber(self): ...
    @property
    def discnumber(self): ...
    @property
    def errors(self): ...
    def error_append(self, msg) -> None: ...
    def clear_errors(self) -> None: ...
    def cover_art_description(self): ...
    def cover_art_description_detailed(self): ...

class FileListItem(Item):
    files: Incomplete
    update_metadata_images_enabled: bool
    def __init__(self, files: Incomplete | None = None) -> None: ...
    def iterfiles(self, save: bool = False) -> Generator[Incomplete, Incomplete]: ...
    def enable_update_metadata_images(self, enabled) -> None: ...
    def update_metadata_images(self) -> None: ...
    def keep_original_images(self) -> None: ...
