from PyQt5 import QtWidgets
from _typeshed import Incomplete
from picard import log as log
from picard.album import Album as Album, NatAlbum as NatAlbum
from picard.cluster import (
    Cluster as Cluster,
    ClusterList as ClusterList,
    UnclusteredFiles as UnclusteredFiles,
)
from picard.config import (
    BoolOption as BoolOption,
    Option as Option,
    get_config as get_config,
)
from picard.file import File as File, FileErrorType as FileErrorType
from picard.i18n import sort_key as sort_key
from picard.plugin import ExtensionPoint as ExtensionPoint
from picard.track import NonAlbumTrack as NonAlbumTrack, Track as Track
from picard.ui.collectionmenu import CollectionMenu as CollectionMenu
from picard.ui.colors import interface_colors as interface_colors
from picard.ui.ratingwidget import RatingWidget as RatingWidget
from picard.ui.scriptsmenu import ScriptsMenu as ScriptsMenu
from picard.ui.widgets.tristatesortheaderview import (
    TristateSortHeaderView as TristateSortHeaderView,
)
from picard.util import (
    icontheme as icontheme,
    iter_files_from_objects as iter_files_from_objects,
    normpath as normpath,
    restore_method as restore_method,
)

COLUMN_ICON_SIZE: int
COLUMN_ICON_BORDER: int
ICON_SIZE: Incomplete

class BaseAction(QtWidgets.QAction):
    NAME: str
    MENU: Incomplete
    def __init__(self) -> None: ...
    def callback(self, objs) -> None: ...

def register_album_action(action) -> None: ...
def register_cluster_action(action) -> None: ...
def register_clusterlist_action(action) -> None: ...
def register_track_action(action) -> None: ...
def register_file_action(action) -> None: ...
def get_match_color(similarity, basecolor): ...

class MainPanel(QtWidgets.QSplitter):
    options: Incomplete
    columns: Incomplete
    TITLE_COLUMN: Incomplete
    TRACKNUMBER_COLUMN: Incomplete
    DISCNUMBER_COLUMN: Incomplete
    LENGTH_COLUMN: Incomplete
    FINGERPRINT_COLUMN: Incomplete
    NAT_SORT_COLUMNS: Incomplete
    window: Incomplete
    def __init__(self, window, parent: Incomplete | None = None) -> None: ...
    def set_processing(self, processing: bool = True) -> None: ...
    def tab_order(self, tab_order, before, after) -> None: ...
    def save_state(self) -> None: ...
    icon_plugins: Incomplete
    def create_icons(self) -> None: ...
    def update_current_view(self) -> None: ...
    def remove(self, objects) -> None: ...
    def set_sorting(self, sort: bool = True) -> None: ...
    def select_object(self, obj) -> None: ...

def paint_column_icon(painter, rect, icon) -> None: ...

class ConfigurableColumnsHeader(TristateSortHeaderView):
    def __init__(self, parent: Incomplete | None = None) -> None: ...
    def show_column(self, column, show) -> None: ...
    def update_visible_columns(self, columns) -> None: ...
    def contextMenuEvent(self, event) -> None: ...
    def restore_defaults(self) -> None: ...
    def paintSection(self, painter, rect, index) -> None: ...
    def on_sort_indicator_changed(self, index, order) -> None: ...
    def lock(self, is_locked) -> None: ...

class BaseTreeView(QtWidgets.QTreeWidget):
    window: Incomplete
    panel: Incomplete
    expand_all_action: Incomplete
    collapse_all_action: Incomplete
    select_all_action: Incomplete
    def __init__(self, window, parent: Incomplete | None = None) -> None: ...
    def contextMenuEvent(self, event) -> None: ...
    def restore_state(self) -> None: ...
    def save_state(self) -> None: ...
    def restore_default_columns(self) -> None: ...
    def supportedDropActions(self): ...
    def mimeTypes(self): ...
    def dragEnterEvent(self, event) -> None: ...
    def dragMoveEvent(self, event) -> None: ...
    def startDrag(self, supportedActions) -> None: ...
    def mimeData(self, items): ...
    def scrollTo(self, index, scrolltype=...) -> None: ...
    @staticmethod
    def drop_urls(urls, target, move_to_multi_tracks: bool = True) -> None: ...
    def dropEvent(self, event) -> None: ...
    def dropMimeData(self, parent, index, data, action): ...
    def activate_item(self, index) -> None: ...
    def add_cluster(self, cluster, parent_item: Incomplete | None = None) -> None: ...
    def moveCursor(self, action, modifiers): ...

class FileTreeView(BaseTreeView):
    header_state: Incomplete
    header_locked: Incomplete
    unmatched_files: Incomplete
    clusters: Incomplete
    def __init__(self, window, parent: Incomplete | None = None) -> None: ...
    def add_file_cluster(
        self, cluster, parent_item: Incomplete | None = None
    ) -> None: ...
    def remove_file_cluster(self, cluster) -> None: ...
    def set_clusters_text(self) -> None: ...

class AlbumTreeView(BaseTreeView):
    header_state: Incomplete
    header_locked: Incomplete
    def __init__(self, window, parent: Incomplete | None = None) -> None: ...
    def add_album(self, album) -> None: ...
    def remove_album(self, album) -> None: ...

class TreeItem(QtWidgets.QTreeWidgetItem):
    obj: Incomplete
    sortable: Incomplete
    def __init__(self, obj, sortable, *args) -> None: ...
    def setText(self, column, text): ...
    def __lt__(self, other): ...
    def sortkey(self, column): ...

class ClusterItem(TreeItem):
    def __init__(self, *args) -> None: ...
    def update(self, update_selection: bool = True) -> None: ...
    def add_file(self, file) -> None: ...
    def add_files(self, files) -> None: ...
    def remove_file(self, file) -> None: ...

class AlbumItem(TreeItem):
    def update(
        self, update_tracks: bool = True, update_selection: bool = True
    ) -> None: ...
    def __lt__(self, other): ...

class NatAlbumItem(AlbumItem):
    def __lt__(self, other): ...

class TrackItem(TreeItem):
    def update(
        self,
        update_album: bool = True,
        update_files: bool = True,
        update_selection: bool = True,
    ) -> None: ...

class FileItem(TreeItem):
    def update(
        self, update_track: bool = True, update_selection: bool = True
    ) -> None: ...
    @staticmethod
    def decide_file_icon_info(file): ...
    @staticmethod
    def decide_fingerprint_icon_info(file): ...
