from PyQt5 import QtWidgets
from _typeshed import Incomplete
from picard import PICARD_APP_ID as PICARD_APP_ID, log as log
from picard.album import Album as Album
from picard.browser import addrelease as addrelease
from picard.cluster import Cluster as Cluster, FileList as FileList
from picard.config import (
    BoolOption as BoolOption,
    FloatOption as FloatOption,
    IntOption as IntOption,
    Option as Option,
    SettingConfigSection as SettingConfigSection,
    TextOption as TextOption,
    get_config as get_config,
)
from picard.const import PROGRAM_UPDATE_LEVELS as PROGRAM_UPDATE_LEVELS
from picard.const.sys import IS_MACOS as IS_MACOS, IS_WIN as IS_WIN
from picard.file import File as File
from picard.formats import supported_formats as supported_formats
from picard.plugin import ExtensionPoint as ExtensionPoint
from picard.script import (
    get_file_naming_script_presets as get_file_naming_script_presets,
)
from picard.track import Track as Track
from picard.ui import PreserveGeometry as PreserveGeometry
from picard.ui.aboutdialog import AboutDialog as AboutDialog
from picard.ui.coverartbox import CoverArtBox as CoverArtBox
from picard.ui.filebrowser import FileBrowser as FileBrowser
from picard.ui.infodialog import (
    AlbumInfoDialog as AlbumInfoDialog,
    ClusterInfoDialog as ClusterInfoDialog,
    FileInfoDialog as FileInfoDialog,
    TrackInfoDialog as TrackInfoDialog,
)
from picard.ui.infostatus import InfoStatus as InfoStatus
from picard.ui.itemviews import BaseTreeView as BaseTreeView, MainPanel as MainPanel
from picard.ui.logview import HistoryView as HistoryView, LogView as LogView
from picard.ui.metadatabox import MetadataBox as MetadataBox
from picard.ui.newuserdialog import NewUserDialog as NewUserDialog
from picard.ui.options.dialog import OptionsDialog as OptionsDialog
from picard.ui.passworddialog import (
    PasswordDialog as PasswordDialog,
    ProxyDialog as ProxyDialog,
)
from picard.ui.pluginupdatedialog import PluginUpdatesDialog as PluginUpdatesDialog
from picard.ui.savewarningdialog import SaveWarningDialog as SaveWarningDialog
from picard.ui.scripteditor import (
    ScriptEditorDialog as ScriptEditorDialog,
    ScriptEditorExamples as ScriptEditorExamples,
)
from picard.ui.searchdialog.album import AlbumSearchDialog as AlbumSearchDialog
from picard.ui.searchdialog.track import TrackSearchDialog as TrackSearchDialog
from picard.ui.statusindicator import DesktopStatusIndicator as DesktopStatusIndicator
from picard.ui.tagsfromfilenames import (
    TagsFromFileNamesDialog as TagsFromFileNamesDialog,
)
from picard.ui.util import (
    MultiDirsSelectDialog as MultiDirsSelectDialog,
    find_starting_directory as find_starting_directory,
)
from picard.util import (
    IgnoreUpdatesContext as IgnoreUpdatesContext,
    icontheme as icontheme,
    iter_files_from_objects as iter_files_from_objects,
    iter_unique as iter_unique,
    open_local_path as open_local_path,
    reconnect as reconnect,
    restore_method as restore_method,
    thread as thread,
    throttle as throttle,
    webbrowser2 as webbrowser2,
)
from picard.util.cdrom import (
    DISCID_NOT_LOADED_MESSAGE as DISCID_NOT_LOADED_MESSAGE,
    discid as discid,
    get_cdrom_drives as get_cdrom_drives,
)

ui_init: Incomplete

def register_ui_init(function) -> None: ...

class MainWindowActions:
    @classmethod
    def add(cls): ...
    @classmethod
    def create(cls, parent) -> None: ...

class MainWindow(QtWidgets.QMainWindow, PreserveGeometry):
    defaultsize: Incomplete
    selection_updated: Incomplete
    ready_for_display: Incomplete
    options: Incomplete
    selected_objects: Incomplete
    ignore_selection_changes: Incomplete
    toolbar: Incomplete
    player: Incomplete
    status_indicators: Incomplete
    script_editor_dialog: Incomplete
    def __init__(
        self, parent: Incomplete | None = None, disable_player: bool = False
    ) -> None: ...
    show_close_window: Incomplete
    panel: Incomplete
    file_browser: Incomplete
    log_dialog: Incomplete
    history_dialog: Incomplete
    metadata_box: Incomplete
    cover_art_box: Incomplete
    metadata_view: Incomplete
    def setupUi(self) -> None: ...
    def set_processing(self, processing: bool = True) -> None: ...
    def set_sorting(self, sorting: bool = True) -> None: ...
    def keyPressEvent(self, event) -> None: ...
    def show(self) -> None: ...
    def showEvent(self, event) -> None: ...
    def closeEvent(self, event) -> None: ...
    def register_status_indicator(self, indicator) -> None: ...
    def show_quit_confirmation(self): ...
    def saveWindowState(self) -> None: ...
    def restoreWindowState(self) -> None: ...
    listening_label: Incomplete
    def create_statusbar(self) -> None: ...
    def update_statusbar_stats(self) -> None: ...
    def update_statusbar_listen_port(self, listen_port) -> None: ...
    def set_statusbar_message(self, message, *args, **kwargs): ...
    def create_actions(self) -> None: ...
    def update_cd_lookup_drives(self, drives) -> None: ...
    def toggle_rename_files(self, checked) -> None: ...
    def toggle_move_files(self, checked) -> None: ...
    def toggle_tag_saving(self, checked) -> None: ...
    def get_selected_or_unmatched_files(self): ...
    def open_tags_from_filenames(self) -> None: ...
    def open_collection_in_browser(self) -> None: ...
    script_quick_selector_menu: Incomplete
    profile_quick_selector_menu: Incomplete
    def create_menus(self) -> None: ...
    def update_toolbar_style(self) -> None: ...
    def create_toolbar(self) -> None: ...
    def create_action_toolbar(self) -> None: ...
    player_toolbar_toggle_action: Incomplete
    def create_player_toolbar(self) -> None: ...
    search_toolbar: Incomplete
    search_toolbar_toggle_action: Incomplete
    search_combo: Incomplete
    search_edit: Incomplete
    search_button: Incomplete
    def create_search_toolbar(self) -> None: ...
    def set_tab_order(self) -> None: ...
    def enable_submit(self, enabled) -> None: ...
    def enable_cluster(self, enabled) -> None: ...
    def enable_search(self) -> None: ...
    def trigger_search_action(self) -> None: ...
    def search_mbid_found(self, entity, mbid) -> None: ...
    def search(self) -> None: ...
    def add_files(self) -> None: ...
    def add_directory(self) -> None: ...
    def close_active_window(self) -> None: ...
    def show_about(self): ...
    def show_options(self, page: Incomplete | None = None): ...
    def options_closed(self) -> None: ...
    def show_help(self) -> None: ...
    def show_log(self) -> None: ...
    def show_history(self) -> None: ...
    def open_bug_report(self) -> None: ...
    def open_support_forum(self) -> None: ...
    def open_donation_page(self) -> None: ...
    def save(self) -> None: ...
    def remove(self) -> None: ...
    def analyze(self) -> None: ...
    def generate_fingerprints(self) -> None: ...
    def play_file(self) -> None: ...
    def open_folder(self) -> None: ...
    def get_first_obj_with_type(self, type): ...
    def show_similar_items_search(self) -> None: ...
    def show_more_tracks(self) -> None: ...
    def show_more_albums(self) -> None: ...
    def show_album_other_versions(self) -> None: ...
    def view_info(self, default_tab: int = 0) -> None: ...
    def cluster(self) -> None: ...
    def refresh(self) -> None: ...
    def browser_lookup(self) -> None: ...
    def submit_cluster(self) -> None: ...
    def submit_file(self, as_release: bool = False) -> None: ...
    def update_actions(self) -> None: ...
    def update_selection(
        self,
        objects: Incomplete | None = None,
        new_selection: bool = True,
        drop_album_caches: bool = False,
    ) -> None: ...
    def refresh_metadatabox(self) -> None: ...
    def show_metadata_view(self) -> None: ...
    def show_cover_art(self) -> None: ...
    def show_toolbar(self) -> None: ...
    def show_file_browser(self) -> None: ...
    def show_password_dialog(self, reply, authenticator) -> None: ...
    def on_mb_login_finished(self, successful, error_msg) -> None: ...
    def show_proxy_dialog(self, proxy, authenticator) -> None: ...
    def autotag(self) -> None: ...
    def copy_files(self, objects) -> None: ...
    def paste_files(self, target) -> None: ...
    def cut(self) -> None: ...
    def paste(self) -> None: ...
    def do_update_check(self) -> None: ...
    def auto_update_check(self) -> None: ...
    def check_for_update(self, show_always) -> None: ...
    def check_and_repair_naming_scripts(self) -> None: ...
    def check_and_repair_profiles(self) -> None: ...
    def make_script_selector_menu(self): ...
    def select_new_naming_script(self, id) -> None: ...
    script_editor_signals: Incomplete
    def open_file_naming_script_editor(self) -> None: ...
    def script_editor_save(self) -> None: ...
    def script_editor_closed(self) -> None: ...
    def update_script_editor_example_files(self) -> None: ...
    def update_script_editor_examples(self) -> None: ...
    def script_editor_index_changed(self) -> None: ...
    def update_selector_from_script_editor(self) -> None: ...
    def make_profile_selector_menu(self) -> None: ...
    def update_profile_selection(self, profile_id) -> None: ...
    def show_new_user_dialog(self) -> None: ...
    def check_for_plugin_update(self) -> None: ...
    def show_plugin_update_dialog(self, plugin_names) -> None: ...
    def show_plugins_options_page(self) -> None: ...

def update_last_check_date(is_success) -> None: ...
