from PyQt5 import QtCore, QtWidgets
from _typeshed import Incomplete
from picard import log as log
from picard.config import get_config as get_config
from picard.const.sys import IS_MACOS as IS_MACOS
from picard.ui.widgets import (
    ClickableSlider as ClickableSlider,
    ElidedLabel as ElidedLabel,
    SliderPopover as SliderPopover,
)
from picard.util import (
    format_time as format_time,
    icontheme as icontheme,
    iter_files_from_objects as iter_files_from_objects,
)

qt_multimedia_available: bool
qt_multimedia_errmsg: Incomplete

def get_logarithmic_volume(player_value): ...
def get_linear_volume(slider_value): ...
def get_text_width(font, text): ...

class Player(QtCore.QObject):
    error: Incomplete
    state_changed: Incomplete
    def __init__(self, parent) -> None: ...
    @property
    def available(self): ...
    @property
    def toolbar(self): ...
    def volume(self): ...
    def playback_rate(self): ...
    def create_toolbar(self): ...
    def set_objects(self, objects) -> None: ...
    def play(self) -> None: ...
    def pause(self, is_paused) -> None: ...
    def set_volume(self, logarithmic_volume) -> None: ...
    def set_position(self, position) -> None: ...
    def set_playback_rate(self, playback_rate) -> None: ...

class PlayerToolbar(QtWidgets.QToolBar):
    player: Incomplete
    play_action: Incomplete
    pause_action: Incomplete
    progress_widget: Incomplete
    volume_button: Incomplete
    playback_rate_button: Incomplete
    def __init__(self, parent, player) -> None: ...
    def play(self) -> None: ...
    def setToolButtonStyle(self, style) -> None: ...
    def showEvent(self, event) -> None: ...

class PlaybackProgressSlider(QtWidgets.QWidget):
    player: Incomplete
    progress_slider: Incomplete
    media_name_label: Incomplete
    position_label: Incomplete
    duration_label: Incomplete
    def __init__(self, parent, player) -> None: ...
    def on_duration_changed(self, duration) -> None: ...
    def on_position_changed(self, position) -> None: ...
    def on_media_changed(self, media) -> None: ...
    def on_value_changed(self, value) -> None: ...

class PlaybackRateButton(QtWidgets.QToolButton):
    playback_rate_changed: Incomplete
    multiplier: float
    popover_position: str
    rate_fmt: Incomplete
    def __init__(self, parent, playback_rate) -> None: ...
    def show_popover(self) -> None: ...
    def on_slider_value_changed(self, value) -> None: ...
    playback_rate: Incomplete
    def set_playback_rate(self, playback_rate) -> None: ...
    def wheelEvent(self, event) -> None: ...

class VolumeControlButton(QtWidgets.QToolButton):
    volume_changed: Incomplete
    popover_position: str
    step: int
    volume_fmt: Incomplete
    def __init__(self, parent, volume) -> None: ...
    def show_popover(self) -> None: ...
    def on_slider_value_changed(self, value) -> None: ...
    volume: Incomplete
    def set_volume(self, volume) -> None: ...
    def update_icon(self) -> None: ...
    def wheelEvent(self, event) -> None: ...
