from PyQt5 import QtWidgets
from _typeshed import Incomplete
from picard import log as log
from picard.config import get_config as get_config

class RatingWidget(QtWidgets.QWidget):
    def __init__(self, parent, track) -> None: ...
    def sizeHint(self): ...
    def mousePressEvent(self, event) -> None: ...
    def mouseMoveEvent(self, event) -> None: ...
    def leaveEvent(self, event) -> None: ...
    def paintEvent(self, event: Incomplete | None = None) -> None: ...
