from PyQt5 import QtGui
from _typeshed import Incomplete
from collections.abc import Generator
from picard import log as log
from picard.config import (
    BoolOption as BoolOption,
    Option as Option,
    SettingConfigSection as SettingConfigSection,
    TextOption as TextOption,
    get_config as get_config,
)
from picard.const import (
    DEFAULT_COPY_TEXT as DEFAULT_COPY_TEXT,
    DEFAULT_NAMING_PRESET_ID as DEFAULT_NAMING_PRESET_ID,
    DEFAULT_SCRIPT_NAME as DEFAULT_SCRIPT_NAME,
    PICARD_URLS as PICARD_URLS,
)
from picard.file import File as File
from picard.metadata import Metadata as Metadata
from picard.script import (
    ScriptError as ScriptError,
    ScriptParser as ScriptParser,
    get_file_naming_script as get_file_naming_script,
    get_file_naming_script_presets as get_file_naming_script_presets,
)
from picard.script.serializer import (
    FileNamingScript as FileNamingScript,
    ScriptImportExportError as ScriptImportExportError,
)
from picard.ui import PicardDialog as PicardDialog, SingletonDialog as SingletonDialog
from picard.ui.options import OptionsPage as OptionsPage
from picard.ui.options.scripting import (
    OptionsCheckError as OptionsCheckError,
    ScriptCheckError as ScriptCheckError,
)
from picard.ui.ui_scripteditor import Ui_ScriptEditor as Ui_ScriptEditor
from picard.ui.ui_scripteditor_details import Ui_ScriptDetails as Ui_ScriptDetails
from picard.ui.widgets.scriptdocumentation import (
    ScriptingDocumentationWidget as ScriptingDocumentationWidget,
)
from picard.util import (
    get_base_title as get_base_title,
    icontheme as icontheme,
    iter_files_from_objects as iter_files_from_objects,
    unique_numbered_title as unique_numbered_title,
    webbrowser2 as webbrowser2,
)
from picard.util.filenaming import WinPathTooLong as WinPathTooLong
from picard.util.settingsoverride import SettingsOverride as SettingsOverride
from typing import NamedTuple

class ScriptFileError(OptionsCheckError): ...

class ScriptEditorExamples:
    max_samples: int
    tagger: Incomplete
    settings: Incomplete
    example_list: Incomplete
    script_text: Incomplete
    def __init__(self, tagger) -> None: ...
    def update_sample_example_files(self) -> None: ...
    def update_examples(
        self, override: Incomplete | None = None, script_text: Incomplete | None = None
    ) -> None: ...
    def update_example_listboxes(self, before_listbox, after_listbox): ...
    def get_examples(self): ...
    @staticmethod
    def synchronize_selected_example_lines(current_row, source, target) -> None: ...
    @classmethod
    def get_notes_text(cls): ...
    @classmethod
    def get_tooltip_text(cls): ...
    @staticmethod
    def default_examples() -> Generator[Incomplete]: ...

def confirmation_dialog(parent, message): ...
def synchronize_vertical_scrollbars(widgets) -> None: ...
def populate_script_selection_combo_box(
    naming_scripts, selected_script_id, combo_box
): ...

class NotEmptyValidator(QtGui.QValidator):
    def validate(self, text: str, pos): ...

class ScriptEditorDialog(PicardDialog, SingletonDialog):
    TITLE: Incomplete
    STYLESHEET_ERROR: Incomplete
    PROFILES_KEY: Incomplete
    SETTINGS_KEY: Incomplete
    SELECTED_SCRIPT_KEY: str
    SCRIPTS_LIST_KEY: str
    help_url: Incomplete
    options: Incomplete
    signal_save: Incomplete
    signal_update: Incomplete
    signal_selection_changed: Incomplete
    signal_index_changed: Incomplete
    default_script_directory: Incomplete
    default_script_filename: str

    class Profile(NamedTuple):
        id: Incomplete
        title: Incomplete
        script_id: Incomplete

    @classmethod
    def show_instance(cls, *args, **kwargs): ...
    examples: Incomplete
    loading: bool
    ui: Incomplete
    reset_button: Incomplete
    save_button: Incomplete
    close_button: Incomplete
    examples_current_row: int
    selected_script_index: int
    current_item_dict: Incomplete
    original_script_id: str
    original_script_title: str
    last_selected_id: str
    def __init__(
        self, parent: Incomplete | None = None, examples: Incomplete | None = None
    ) -> None: ...
    def setParent(self, parent) -> None: ...
    import_action: Incomplete
    export_action: Incomplete
    reset_action: Incomplete
    save_action: Incomplete
    close_action: Incomplete
    details_action: Incomplete
    add_action: Incomplete
    copy_action: Incomplete
    delete_action: Incomplete
    examples_action: Incomplete
    docs_action: Incomplete
    help_action: Incomplete
    scripting_docs_action: Incomplete
    def make_menu(self) -> None: ...
    def make_script_template_selector_menu(self) -> None: ...
    def is_options_ui(self): ...
    def is_main_ui(self): ...
    naming_scripts: Incomplete
    selected_script_id: Incomplete
    def load(self, reload: bool = False) -> None: ...
    def all_scripts(self, scripts: Incomplete | None = None): ...
    def reload_from_config(self) -> None: ...
    def docs_browser(self) -> None: ...
    def eventFilter(self, object, event): ...
    def closeEvent(self, event) -> None: ...
    def unsaved_changes_in_profile_confirmation(self): ...
    def reset_script_in_settings(self) -> None: ...
    def reset_script_in_profiles(self) -> None: ...
    def unsaved_scripts(self) -> Generator[Incomplete]: ...
    def scripts_in_profiles(self): ...
    def update_script_text(self) -> None: ...
    def check_duplicate_script_title(self, new_title: Incomplete | None = None): ...
    def update_script_title(self) -> None: ...
    def populate_script_selector(self) -> None: ...
    def toggle_documentation(self) -> None: ...
    def view_script_details(self) -> None: ...
    def update_from_details(self) -> None: ...
    def new_script_name(self, base_title: Incomplete | None = None): ...
    def new_script(self, script) -> None: ...
    def copy_script(self) -> None: ...
    def make_it_so(self) -> None: ...
    def get_scripts_dict(self): ...
    def get_selected_item(self, idx: Incomplete | None = None): ...
    def set_selected_script_id(self, id) -> None: ...
    def set_selected_script_index(self, idx) -> None: ...
    def select_script(self, update_last_selected: bool = True) -> None: ...
    def update_combo_box_item(self, idx, script_item) -> None: ...
    def set_selector_states(self, save_enabled: bool = True) -> None: ...
    def set_button_states(self, save_enabled: bool = True) -> None: ...
    def match_after_to_before(self) -> None: ...
    def match_before_to_after(self) -> None: ...
    def delete_script(self) -> None: ...
    def is_used_in_profile(
        self, script_id: Incomplete | None = None, profiles: Incomplete | None = None
    ): ...
    def save_script(self) -> None: ...
    def get_script(self): ...
    def update_example_files(self) -> None: ...
    def update_examples(self, script_text: Incomplete | None = None) -> None: ...
    def display_examples(self) -> None: ...
    def output_file_error(self, fmt, filename, msg) -> None: ...
    def import_script(self) -> None: ...
    def export_script(self) -> None: ...
    def check_formats(self) -> None: ...
    def check_format(self) -> None: ...
    def display_error(self, error) -> None: ...
    def test(self) -> None: ...

class ScriptDetailsEditor(PicardDialog):
    NAME: str
    TITLE: Incomplete
    signal_save: Incomplete
    script_item: Incomplete
    ui: Incomplete
    skip_change_check: bool
    def __init__(self, parent, script_item) -> None: ...
    def has_changed(self): ...
    def change_check(self): ...
    def set_last_updated(self) -> None: ...
    def save_changes(self) -> None: ...
    def close_window(self) -> None: ...
    def closeEvent(self, event) -> None: ...
