from PyQt5.QtCore import QObject
from PyQt5.QtDBus import QDBusAbstractAdaptor
from _typeshed import Incomplete
from picard import PICARD_DESKTOP_NAME as PICARD_DESKTOP_NAME
from picard.const.sys import (
    IS_HAIKU as IS_HAIKU,
    IS_MACOS as IS_MACOS,
    IS_WIN as IS_WIN,
)

DesktopStatusIndicator: Incomplete

class AbstractProgressStatusIndicator:
    def __init__(self) -> None: ...
    def update(
        self,
        files: int = 0,
        albums: int = 0,
        pending_files: int = 0,
        pending_requests: int = 0,
        progress: int = 0,
    ) -> None: ...
    @property
    def is_available(self): ...
    def hide_progress(self) -> None: ...
    def set_progress(self, progress) -> None: ...

class WindowsTaskbarStatusIndicator(AbstractProgressStatusIndicator):
    def __init__(self, window) -> None: ...
    @property
    def is_available(self): ...
    def hide_progress(self) -> None: ...
    def set_progress(self, progress) -> None: ...

DesktopStatusIndicator = WindowsTaskbarStatusIndicator
QDBusConnection: Incomplete
DBUS_INTERFACE: str

class UnityLauncherEntryService(QObject):
    def __init__(self, bus, app_id) -> None: ...
    @property
    def current_progress(self): ...
    @property
    def is_available(self): ...
    def update(self, progress, visible: bool = True) -> None: ...
    def query(self): ...

class UnityLauncherEntryAdaptor(QDBusAbstractAdaptor):
    def __init__(self, parent) -> None: ...
    def query(self): ...

class UnityLauncherEntryStatusIndicator(AbstractProgressStatusIndicator):
    def __init__(self, window) -> None: ...
    @property
    def is_available(self): ...
    def hide_progress(self) -> None: ...
    def set_progress(self, progress) -> None: ...

DesktopStatusIndicator = UnityLauncherEntryStatusIndicator
