import abc
from PyQt5 import QtWidgets
from _typeshed import Incomplete
from abc import abstractmethod
from picard import log as log
from picard.config import get_config as get_config
from picard.i18n import sort_key as sort_key
from picard.ui import PicardDialog as PicardDialog
from picard.ui.theme import theme as theme
from picard.util import restore_method as restore_method, throttle as throttle

class ResultTable(QtWidgets.QTableWidget):
    def __init__(self, parent) -> None: ...
    def prepare(self, headers) -> None: ...

class SortableTableWidgetItem(QtWidgets.QTableWidgetItem):
    sort_key: Incomplete
    def __init__(self, sort_key) -> None: ...
    def __lt__(self, other): ...

class TableBasedDialog(PicardDialog, metaclass=abc.ABCMeta):
    defaultsize: Incomplete
    scrolled: Incomplete
    sorting_enabled: bool
    def __init__(self, parent) -> None: ...
    @property
    def columns(self): ...
    @columns.setter
    def columns(self, list_of_tuples) -> None: ...
    @property
    def table_headers(self): ...
    def colpos(self, colname): ...
    @abstractmethod
    def get_value_for_row_id(self, row, value): ...
    def set_table_item(
        self, row, colname, obj, key, sortkey: Incomplete | None = None
    ) -> None: ...
    def set_table_item_val(
        self, row, colname, value, sortkey: Incomplete | None = None
    ) -> None: ...
    @abstractmethod
    def setupUi(self): ...
    def add_widget_to_center_layout(self, widget) -> None: ...
    def create_table_obj(self): ...
    table: Incomplete
    def create_table(self) -> None: ...
    def highlight_row(self, row) -> None: ...
    def prepare_table(self) -> None: ...
    def show_table(
        self, sort_column: Incomplete | None = None, sort_order=...
    ) -> None: ...
    def accept(self) -> None: ...
    def restore_table_header_state(self) -> None: ...
    def save_state(self) -> None: ...
    def save_table_header_state(self) -> None: ...
