from _typeshed import Incomplete
from mutagen.id3 import ID3, TextFrame

class GRP1(TextFrame): ...
class XSOP(TextFrame): ...

known_frames: Incomplete

class CompatID3(ID3):
    PEDANTIC: bool
    def __init__(self, *args, **kwargs) -> None: ...
    def update_to_v23(self) -> None: ...

def update_to_v23(tags) -> None: ...
