from PyQt5 import QtCore
from _typeshed import Incomplete
from collections.abc import Generator
from picard import log as log
from picard.const import (
    DEFAULT_COPY_TEXT as DEFAULT_COPY_TEXT,
    DEFAULT_NUMBERED_TITLE_FORMAT as DEFAULT_NUMBERED_TITLE_FORMAT,
    MUSICBRAINZ_SERVERS as MUSICBRAINZ_SERVERS,
)
from picard.const.sys import (
    FROZEN_TEMP_PATH as FROZEN_TEMP_PATH,
    IS_FROZEN as IS_FROZEN,
    IS_MACOS as IS_MACOS,
    IS_WIN as IS_WIN,
)
from typing import NamedTuple
import types

WIN_MAX_FILEPATH_LEN: int
WIN_MAX_DIRPATH_LEN: Incomplete
WIN_MAX_NODE_LEN: int
WIN_LONGPATH_PREFIX: str

class ReadWriteLockContext:
    def __init__(self) -> None: ...
    def lock_for_read(self): ...
    def lock_for_write(self): ...
    def unlock(self) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        type: type[BaseException] | None,
        value: BaseException | None,
        tb: types.TracebackType | None,
    ) -> None: ...
    def __bool__(self) -> bool: ...

class LockableObject(QtCore.QObject):
    def __init__(self) -> None: ...
    def lock_for_read(self): ...
    def lock_for_write(self): ...
    def unlock(self) -> None: ...

def process_events_iter(iterable, interval: float = 0.1) -> Generator[Incomplete]: ...
def iter_files_from_objects(objects, save: bool = False): ...
def check_io_encoding() -> None: ...
def encode_filename(filename): ...
def decode_filename(filename): ...
def system_supports_long_paths(): ...
def normpath(path, realpath: bool = True): ...
def win_prefix_longpath(path): ...
def is_absolute_path(path): ...
def samepath(path1, path2): ...
def samefile(path1, path2): ...
def format_time(ms, display_zero: bool = False): ...
def sanitize_date(datestr): ...
def replace_win32_incompat(
    string, repl: str = "_", replacements: Incomplete | None = None
): ...
def strip_non_alnum(string): ...
def sanitize_filename(string, repl: str = "_", win_compat: bool = False): ...
def make_filename_from_title(
    title: Incomplete | None = None, default: Incomplete | None = None
): ...
def translate_from_sortname(name, sortname): ...
def find_existing_path(path): ...
def find_executable(*executables): ...
def run_executable(executable, *args, timeout: Incomplete | None = None): ...
def open_local_path(path) -> None: ...
def mbid_validate(string): ...
def parse_amazon_url(url): ...
def throttle(interval): ...

class IgnoreUpdatesContext:
    def __init__(self, onexit: Incomplete | None = None) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        type: type[BaseException] | None,
        value: BaseException | None,
        tb: types.TracebackType | None,
    ) -> None: ...
    def __bool__(self) -> bool: ...

def uniqify(seq): ...
def iter_unique(seq): ...
def tracknum_from_filename(base_filename): ...

class GuessedFromFilename(NamedTuple):
    tracknumber: Incomplete
    title: Incomplete

def tracknum_and_title_from_filename(base_filename): ...
def is_hidden(filepath): ...
def linear_combination_of_weights(parts): ...
def album_artist_from_path(filename, album, artist): ...
def encoded_queryargs(queryargs): ...
def build_qurl(
    host,
    port: int = 80,
    path: Incomplete | None = None,
    queryargs: Incomplete | None = None,
): ...
def union_sorted_lists(list1, list2): ...
def load_json(data): ...
def parse_json(reply): ...
def restore_method(func): ...
def reconnect(
    signal, newhandler: Incomplete | None = None, oldhandler: Incomplete | None = None
) -> None: ...
def compare_barcodes(barcode1, barcode2): ...

class BestMatch(NamedTuple):
    similarity: Incomplete
    result: Incomplete

def sort_by_similarity(candidates): ...
def find_best_match(candidates, no_match): ...
def get_qt_enum(cls, attr_class) -> Generator[Incomplete]: ...
def limited_join(a_list, limit, join_string: str = "+", middle_string: str = "…"): ...
def countries_shortlist(countries): ...
def extract_year_from_date(dt): ...
def pattern_as_regex(pattern, allow_wildcards: bool = False, flags: int = 0): ...
def wildcards_to_regex_pattern(pattern): ...
def unique_numbered_title(
    default_title, existing_titles, fmt: Incomplete | None = None
): ...
def get_base_title_with_suffix(title, suffix, fmt: Incomplete | None = None): ...
def get_base_title(title): ...
def iter_exception_chain(err) -> Generator[Incomplete, Incomplete]: ...
def any_exception_isinstance(error, type_): ...

ENCODING_BOMS: Incomplete

def detect_file_encoding(path, max_bytes_to_read=...): ...
def iswbound(char): ...
def titlecase(text): ...
