class BitReaderError(Exception): ...

class _BitReader:
    def __init__(self, fileobj) -> None: ...
    def bits(self, count) -> None: ...
    def bytes(self, count): ...
    def skip(self, count) -> None: ...
    def get_position(self): ...
    def align(self): ...
    def is_aligned(self): ...

class MSBBitReader(_BitReader):
    def bits(self, count): ...

class LSBBitReader(_BitReader):
    def bits(self, count): ...
