def decimal(number, scale: int = 1, l10n: bool = True): ...
def binary(number, scale: int = 1, l10n: bool = True): ...
def short_string(number, multiple, scale: int = 1, l10n: bool = True): ...
def calc_unit(number, multiple: int = 1000): ...
