from _typeshed import Incomplete
from collections.abc import Generator, MutableSequence
from picard.config import get_config as get_config

class ImageList(MutableSequence):
    def __init__(self, iterable=()) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index): ...
    def __setitem__(self, index, value) -> None: ...
    def __delitem__(self, index) -> None: ...
    def insert(self, index, value): ...
    def __eq__(self, other): ...
    def copy(self): ...
    def get_front_image(self): ...
    def to_be_saved_to_tags(
        self, settings: Incomplete | None = None
    ) -> Generator[Incomplete]: ...
    def strip_front_images(self) -> None: ...
    def hash_dict(self): ...

class ImageListState:
    new_images: Incomplete
    orig_images: Incomplete
    sources: Incomplete
    has_common_new_images: bool
    has_common_orig_images: bool
    first_new_obj: bool
    first_orig_obj: bool
    update_new_metadata: bool
    update_orig_metadata: bool
    def __init__(self) -> None: ...

def update_metadata_images(obj): ...
def add_metadata_images(obj, added_sources): ...
def remove_metadata_images(obj, removed_sources) -> None: ...
