from _typeshed import Incomplete
from picard import log as log

TOUCH_FILES_DELAY_SECONDS: Incomplete

def register_file(filepath) -> None: ...
def unregister_file(filepath) -> None: ...
def enable_timer() -> None: ...
