from picard.config import get_config as get_config

class PreservedTags:
    opt_name: str
    def __init__(self) -> None: ...
    def add(self, name) -> None: ...
    def discard(self, name) -> None: ...
    def __contains__(self, key) -> bool: ...
