from _typeshed import Incomplete

class ProgressCheckpoints:
    num_jobs: Incomplete
    def __init__(self, num_jobs, num_checkpoints: int = 10) -> None: ...
    def is_checkpoint(self, index): ...
    def progress(self, index): ...
