from _typeshed import Incomplete
from collections.abc import MutableMapping

class SettingsOverride(MutableMapping):
    orig_settings: Incomplete
    def __init__(self, orig_settings, *args, **kwargs) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
