from picard.util import sanitize_filename as sanitize_filename

def unicode_simplify_compatibility(
    string, pathsave: bool = False, win_compat: bool = False
): ...
def unicode_simplify_punctuation(
    string, pathsave: bool = False, win_compat: bool = False
): ...
def unicode_simplify_combinations(
    string, pathsave: bool = False, win_compat: bool = False
): ...
def unicode_simplify_accents(string): ...
def asciipunct(string): ...
def unaccent(string): ...
def replace_non_ascii(
    string, repl: str = "_", pathsave: bool = False, win_compat: bool = False
): ...
