from picard import PICARD_FANCY_VERSION_STR as PICARD_FANCY_VERSION_STR
from picard.disc import discid_version as discid_version
from picard.util.astrcmp import astrcmp_implementation as astrcmp_implementation

def version_name(key): ...
def as_dict(i18n: bool = False): ...
def as_string(i18n: bool = False, separator: str = ", "): ...
