from _typeshed import Incomplete

class XmlNode:
    text: str
    children: Incomplete
    attribs: Incomplete
    def __init__(self) -> None: ...
    def append_child(self, name, node: Incomplete | None = None): ...
    def __getattr__(self, name): ...

def parse_xml(response): ...
