from _typeshed import Incomplete
from picard import PICARD_VERSION as PICARD_VERSION
from picard.const import appdirs as appdirs
from picard.const.attributes import MB_ATTRIBUTES as MB_ATTRIBUTES
from picard.const.countries import RELEASE_COUNTRIES as RELEASE_COUNTRIES
from picard.const.languages import UI_LANGUAGES as UI_LANGUAGES
from picard.const.locales import ALIAS_LOCALES as ALIAS_LOCALES
from picard.const.scripts import SCRIPTS as SCRIPTS

USER_DIR: Incomplete
USER_PLUGIN_DIR: Incomplete
CACHE_SIZE_IN_BYTES: Incomplete
ACOUSTID_KEY: str
ACOUSTID_URL: str
FPCALC_NAMES: Incomplete
DEFAULT_FPCALC_THREADS: int
MUSICBRAINZ_OAUTH_CLIENT_ID: str
MUSICBRAINZ_OAUTH_CLIENT_SECRET: str
CAA_URL: str
DOCS_VERSION: Incomplete
DOCS_LANGUAGE: str
DOCS_SERVER_URL: str
DOCS_BASE_URL: Incomplete
PICARD_URLS: Incomplete
VARIOUS_ARTISTS_ID: str
ALIAS_TYPE_ARTIST_NAME_ID: str
ALIAS_TYPE_LEGAL_NAME_ID: str
ALIAS_TYPE_SEARCH_HINT_ID: str
SILENCE_TRACK_TITLE: str
DATA_TRACK_TITLE: str
RELEASE_FORMATS: Incomplete
RELEASE_PRIMARY_GROUPS: Incomplete
RELEASE_SECONDARY_GROUPS: Incomplete
RELEASE_STATUS: Incomplete
MUSICBRAINZ_SERVERS: Incomplete
PLUGINS_API_BASE_URL: str
PLUGINS_API: Incomplete
QUERY_LIMIT: int
MAX_COVERS_TO_STACK: int
PROGRAM_UPDATE_LEVELS: Incomplete
DEFAULT_PROGRAM_UPDATE_LEVEL: int
DEFAULT_FILE_NAMING_FORMAT: str
DEFAULT_SCRIPT_NAME: Incomplete
DEFAULT_COVER_IMAGE_FILENAME: str
DEFAULT_PROFILE_NAME: Incomplete
DEFAULT_COPY_TEXT: Incomplete
DEFAULT_NUMBERED_TITLE_FORMAT: Incomplete
DEFAULT_NAMING_PRESET_ID: str
SCRIPT_LANGUAGE_VERSION: str
DEFAULT_TIME_FORMAT: str
