name: test
on:
  push:
  workflow_dispatch:
jobs:
  flake-check:
    runs-on: ubuntu-latest
    env:
      # Required since qt5.qtwebengine is deprecated
      NIXPKGS_ALLOW_INSECURE: 1
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_version: "2.31.2"
      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: cache-test-${{ runner.os }}-nix-store-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: cache-test-${{ runner.os }}-nix-store-
      - name: Run tests
        run: |
          nix flake check --impure '.?submodules=1'
      - name: Run pytest
        run: |
          nix develop --impure --command bash -c "pytest"
